// Code generated by protoc-gen-go. DO NOT EDIT.
// source: devicecallback/devicecallback.proto

package devicecallback

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	driverdevice "github.com/winc-link/edge-driver-proto/driverdevice"
	_ "google.golang.org/protobuf/types/known/emptypb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateDeviceCallbackRequest struct {
	Data                 *driverdevice.Device `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
	HappenTime           uint64               `protobuf:"varint,2,opt,name=happenTime,proto3" json:"happenTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CreateDeviceCallbackRequest) Reset()         { *m = CreateDeviceCallbackRequest{} }
func (m *CreateDeviceCallbackRequest) String() string { return proto.CompactTextString(m) }
func (*CreateDeviceCallbackRequest) ProtoMessage()    {}
func (*CreateDeviceCallbackRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_55bd9305e490c7d0, []int{0}
}

func (m *CreateDeviceCallbackRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateDeviceCallbackRequest.Unmarshal(m, b)
}
func (m *CreateDeviceCallbackRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateDeviceCallbackRequest.Marshal(b, m, deterministic)
}
func (m *CreateDeviceCallbackRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateDeviceCallbackRequest.Merge(m, src)
}
func (m *CreateDeviceCallbackRequest) XXX_Size() int {
	return xxx_messageInfo_CreateDeviceCallbackRequest.Size(m)
}
func (m *CreateDeviceCallbackRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateDeviceCallbackRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateDeviceCallbackRequest proto.InternalMessageInfo

func (m *CreateDeviceCallbackRequest) GetData() *driverdevice.Device {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *CreateDeviceCallbackRequest) GetHappenTime() uint64 {
	if m != nil {
		return m.HappenTime
	}
	return 0
}

type UpdateDeviceCallbackRequest struct {
	Data                 *driverdevice.Device `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
	HappenTime           uint64               `protobuf:"varint,2,opt,name=happenTime,proto3" json:"happenTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *UpdateDeviceCallbackRequest) Reset()         { *m = UpdateDeviceCallbackRequest{} }
func (m *UpdateDeviceCallbackRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateDeviceCallbackRequest) ProtoMessage()    {}
func (*UpdateDeviceCallbackRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_55bd9305e490c7d0, []int{1}
}

func (m *UpdateDeviceCallbackRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateDeviceCallbackRequest.Unmarshal(m, b)
}
func (m *UpdateDeviceCallbackRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateDeviceCallbackRequest.Marshal(b, m, deterministic)
}
func (m *UpdateDeviceCallbackRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateDeviceCallbackRequest.Merge(m, src)
}
func (m *UpdateDeviceCallbackRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateDeviceCallbackRequest.Size(m)
}
func (m *UpdateDeviceCallbackRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateDeviceCallbackRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateDeviceCallbackRequest proto.InternalMessageInfo

func (m *UpdateDeviceCallbackRequest) GetData() *driverdevice.Device {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *UpdateDeviceCallbackRequest) GetHappenTime() uint64 {
	if m != nil {
		return m.HappenTime
	}
	return 0
}

type DeleteDeviceCallbackRequest struct {
	DeviceId             string   `protobuf:"bytes,1,opt,name=deviceId,proto3" json:"deviceId,omitempty"`
	HappenTime           uint64   `protobuf:"varint,2,opt,name=happenTime,proto3" json:"happenTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteDeviceCallbackRequest) Reset()         { *m = DeleteDeviceCallbackRequest{} }
func (m *DeleteDeviceCallbackRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteDeviceCallbackRequest) ProtoMessage()    {}
func (*DeleteDeviceCallbackRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_55bd9305e490c7d0, []int{2}
}

func (m *DeleteDeviceCallbackRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteDeviceCallbackRequest.Unmarshal(m, b)
}
func (m *DeleteDeviceCallbackRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteDeviceCallbackRequest.Marshal(b, m, deterministic)
}
func (m *DeleteDeviceCallbackRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteDeviceCallbackRequest.Merge(m, src)
}
func (m *DeleteDeviceCallbackRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteDeviceCallbackRequest.Size(m)
}
func (m *DeleteDeviceCallbackRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteDeviceCallbackRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteDeviceCallbackRequest proto.InternalMessageInfo

func (m *DeleteDeviceCallbackRequest) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

func (m *DeleteDeviceCallbackRequest) GetHappenTime() uint64 {
	if m != nil {
		return m.HappenTime
	}
	return 0
}

type BatchCreateDeviceCallback struct {
	Data                 []*driverdevice.Device `protobuf:"bytes,1,rep,name=Data,proto3" json:"Data,omitempty"`
	HappenTime           uint64                 `protobuf:"varint,2,opt,name=happenTime,proto3" json:"happenTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *BatchCreateDeviceCallback) Reset()         { *m = BatchCreateDeviceCallback{} }
func (m *BatchCreateDeviceCallback) String() string { return proto.CompactTextString(m) }
func (*BatchCreateDeviceCallback) ProtoMessage()    {}
func (*BatchCreateDeviceCallback) Descriptor() ([]byte, []int) {
	return fileDescriptor_55bd9305e490c7d0, []int{3}
}

func (m *BatchCreateDeviceCallback) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BatchCreateDeviceCallback.Unmarshal(m, b)
}
func (m *BatchCreateDeviceCallback) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BatchCreateDeviceCallback.Marshal(b, m, deterministic)
}
func (m *BatchCreateDeviceCallback) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BatchCreateDeviceCallback.Merge(m, src)
}
func (m *BatchCreateDeviceCallback) XXX_Size() int {
	return xxx_messageInfo_BatchCreateDeviceCallback.Size(m)
}
func (m *BatchCreateDeviceCallback) XXX_DiscardUnknown() {
	xxx_messageInfo_BatchCreateDeviceCallback.DiscardUnknown(m)
}

var xxx_messageInfo_BatchCreateDeviceCallback proto.InternalMessageInfo

func (m *BatchCreateDeviceCallback) GetData() []*driverdevice.Device {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *BatchCreateDeviceCallback) GetHappenTime() uint64 {
	if m != nil {
		return m.HappenTime
	}
	return 0
}

type BatchDeleteDeviceCallback struct {
	DeviceId             []string `protobuf:"bytes,1,rep,name=deviceId,proto3" json:"deviceId,omitempty"`
	HappenTime           uint64   `protobuf:"varint,2,opt,name=happenTime,proto3" json:"happenTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BatchDeleteDeviceCallback) Reset()         { *m = BatchDeleteDeviceCallback{} }
func (m *BatchDeleteDeviceCallback) String() string { return proto.CompactTextString(m) }
func (*BatchDeleteDeviceCallback) ProtoMessage()    {}
func (*BatchDeleteDeviceCallback) Descriptor() ([]byte, []int) {
	return fileDescriptor_55bd9305e490c7d0, []int{4}
}

func (m *BatchDeleteDeviceCallback) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BatchDeleteDeviceCallback.Unmarshal(m, b)
}
func (m *BatchDeleteDeviceCallback) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BatchDeleteDeviceCallback.Marshal(b, m, deterministic)
}
func (m *BatchDeleteDeviceCallback) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BatchDeleteDeviceCallback.Merge(m, src)
}
func (m *BatchDeleteDeviceCallback) XXX_Size() int {
	return xxx_messageInfo_BatchDeleteDeviceCallback.Size(m)
}
func (m *BatchDeleteDeviceCallback) XXX_DiscardUnknown() {
	xxx_messageInfo_BatchDeleteDeviceCallback.DiscardUnknown(m)
}

var xxx_messageInfo_BatchDeleteDeviceCallback proto.InternalMessageInfo

func (m *BatchDeleteDeviceCallback) GetDeviceId() []string {
	if m != nil {
		return m.DeviceId
	}
	return nil
}

func (m *BatchDeleteDeviceCallback) GetHappenTime() uint64 {
	if m != nil {
		return m.HappenTime
	}
	return 0
}

func init() {
	proto.RegisterType((*CreateDeviceCallbackRequest)(nil), "devicecallback.createDeviceCallbackRequest")
	proto.RegisterType((*UpdateDeviceCallbackRequest)(nil), "devicecallback.updateDeviceCallbackRequest")
	proto.RegisterType((*DeleteDeviceCallbackRequest)(nil), "devicecallback.deleteDeviceCallbackRequest")
	proto.RegisterType((*BatchCreateDeviceCallback)(nil), "devicecallback.batchCreateDeviceCallback")
	proto.RegisterType((*BatchDeleteDeviceCallback)(nil), "devicecallback.batchDeleteDeviceCallback")
}

func init() {
	proto.RegisterFile("devicecallback/devicecallback.proto", fileDescriptor_55bd9305e490c7d0)
}

var fileDescriptor_55bd9305e490c7d0 = []byte{
	// 352 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x94, 0xdf, 0x4b, 0xfb, 0x30,
	0x14, 0xc5, 0xbf, 0xfb, 0x6e, 0x88, 0x46, 0xf0, 0xa1, 0x4c, 0xd9, 0x3a, 0x90, 0x31, 0x5f, 0x26,
	0xb2, 0x14, 0x26, 0xe2, 0xfb, 0x36, 0x1f, 0x7c, 0xad, 0x8a, 0x28, 0x08, 0xa6, 0xc9, 0xb5, 0x0d,
	0xfd, 0x69, 0x4d, 0x27, 0xfe, 0xe7, 0x3e, 0x4a, 0x93, 0xaa, 0x5d, 0x97, 0x56, 0x45, 0xf0, 0xf1,
	0xde, 0xde, 0x7b, 0x3e, 0x39, 0xc9, 0xa1, 0xe8, 0x80, 0xc1, 0x92, 0x53, 0xa0, 0x24, 0x08, 0x1c,
	0x42, 0x7d, 0x6b, 0xb5, 0xc4, 0x49, 0x1a, 0x8b, 0xd8, 0xd8, 0x59, 0xed, 0x9a, 0x7d, 0x96, 0xf2,
	0x25, 0xa4, 0xaa, 0x5b, 0xac, 0xa8, 0x51, 0x73, 0xe0, 0xc6, 0xb1, 0x1b, 0x80, 0x25, 0x2b, 0x27,
	0x7b, 0xb0, 0x20, 0x4c, 0xc4, 0x8b, 0xfa, 0x38, 0x72, 0xd1, 0x80, 0xa6, 0x40, 0x04, 0x2c, 0xe4,
	0xca, 0xbc, 0xd0, 0xb3, 0xe1, 0x31, 0x83, 0x27, 0x61, 0x8c, 0x51, 0x67, 0x41, 0x04, 0xe9, 0xb5,
	0x86, 0xad, 0xf1, 0xf6, 0xb4, 0x8b, 0xcb, 0x14, 0xac, 0x56, 0x6c, 0x39, 0x61, 0xec, 0x23, 0xe4,
	0x91, 0x24, 0x81, 0xe8, 0x92, 0x87, 0xd0, 0xfb, 0x3f, 0x6c, 0x8d, 0x3b, 0x76, 0xa9, 0x93, 0x83,
	0xb2, 0x84, 0xfd, 0x01, 0xe8, 0x06, 0x0d, 0x18, 0x04, 0x50, 0x07, 0x32, 0xd1, 0xa6, 0x52, 0x3d,
	0x67, 0x12, 0xb6, 0x65, 0x7f, 0xd4, 0x5f, 0x4a, 0x03, 0xea, 0x3b, 0x44, 0x50, 0x6f, 0xae, 0xb9,
	0xb1, 0x92, 0x83, 0xf6, 0x2f, 0x1d, 0x5c, 0x17, 0x98, 0x85, 0xc6, 0x46, 0xe5, 0xfc, 0xed, 0x9f,
	0x9c, 0x7f, 0xfa, 0xda, 0x46, 0xbb, 0x9f, 0x72, 0x33, 0x42, 0xfd, 0x0b, 0x48, 0xf3, 0xd2, 0xb8,
	0x43, 0x5d, 0xad, 0xa9, 0x23, 0x5c, 0x49, 0x5f, 0x43, 0x58, 0xcc, 0x3d, 0xac, 0x92, 0x86, 0xdf,
	0x93, 0x86, 0xcf, 0xf2, 0xa4, 0x8d, 0xfe, 0xe5, 0xf2, 0x57, 0x9a, 0xc7, 0x5f, 0x97, 0x6f, 0x88,
	0x48, 0xb3, 0xbc, 0xf6, 0xae, 0xd6, 0xe4, 0x1b, 0x82, 0xd1, 0x20, 0x7f, 0x8f, 0xfa, 0xb3, 0xda,
	0x67, 0x3f, 0xac, 0x32, 0x6a, 0x13, 0xf2, 0x0d, 0x82, 0xd6, 0x85, 0x9e, 0xa0, 0x1b, 0xad, 0x27,
	0xcc, 0x4e, 0x6f, 0x4f, 0x5c, 0x2e, 0xbc, 0xcc, 0xc1, 0x34, 0x0e, 0xad, 0x67, 0x1e, 0xd1, 0x49,
	0xc0, 0x23, 0xdf, 0x02, 0xe6, 0xc2, 0x44, 0x45, 0x75, 0x22, 0x97, 0x2a, 0xbf, 0x1b, 0x67, 0x43,
	0x76, 0x8f, 0xdf, 0x02, 0x00, 0x00, 0xff, 0xff, 0x0c, 0x08, 0xe4, 0x63, 0x96, 0x04, 0x00, 0x00,
}
