// Code generated by protoc-gen-go. DO NOT EDIT.
// source: driverdevice/device.proto

package driverdevice

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	drivercommon "github.com/winc-link/edge-driver-proto/drivercommon"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DeviceStatus int32

const (
	DeviceStatus_UnKnowStatus DeviceStatus = 0
	DeviceStatus_OnLine       DeviceStatus = 1
	DeviceStatus_OffLine      DeviceStatus = 2
	DeviceStatus_UnActive     DeviceStatus = 3
	DeviceStatus_Disable      DeviceStatus = 4
)

var DeviceStatus_name = map[int32]string{
	0: "UnKnowStatus",
	1: "OnLine",
	2: "OffLine",
	3: "UnActive",
	4: "Disable",
}

var DeviceStatus_value = map[string]int32{
	"UnKnowStatus": 0,
	"OnLine":       1,
	"OffLine":      2,
	"UnActive":     3,
	"Disable":      4,
}

func (x DeviceStatus) String() string {
	return proto.EnumName(DeviceStatus_name, int32(x))
}

func (DeviceStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d977e3d1d866a4e5, []int{0}
}

type ConnectStatus int32

const (
	ConnectStatus_ONLINE  ConnectStatus = 0
	ConnectStatus_OFFLINE ConnectStatus = 1
)

var ConnectStatus_name = map[int32]string{
	0: "ONLINE",
	1: "OFFLINE",
}

var ConnectStatus_value = map[string]int32{
	"ONLINE":  0,
	"OFFLINE": 1,
}

func (x ConnectStatus) String() string {
	return proto.EnumName(ConnectStatus_name, int32(x))
}

func (ConnectStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d977e3d1d866a4e5, []int{1}
}

type ConnectIotPlatformRequest struct {
	BaseRequest          *drivercommon.BaseRequestMessage `protobuf:"bytes,1,opt,name=baseRequest,proto3" json:"baseRequest,omitempty"`
	DeviceId             string                           `protobuf:"bytes,2,opt,name=deviceId,proto3" json:"deviceId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *ConnectIotPlatformRequest) Reset()         { *m = ConnectIotPlatformRequest{} }
func (m *ConnectIotPlatformRequest) String() string { return proto.CompactTextString(m) }
func (*ConnectIotPlatformRequest) ProtoMessage()    {}
func (*ConnectIotPlatformRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d977e3d1d866a4e5, []int{0}
}

func (m *ConnectIotPlatformRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectIotPlatformRequest.Unmarshal(m, b)
}
func (m *ConnectIotPlatformRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectIotPlatformRequest.Marshal(b, m, deterministic)
}
func (m *ConnectIotPlatformRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectIotPlatformRequest.Merge(m, src)
}
func (m *ConnectIotPlatformRequest) XXX_Size() int {
	return xxx_messageInfo_ConnectIotPlatformRequest.Size(m)
}
func (m *ConnectIotPlatformRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectIotPlatformRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectIotPlatformRequest proto.InternalMessageInfo

func (m *ConnectIotPlatformRequest) GetBaseRequest() *drivercommon.BaseRequestMessage {
	if m != nil {
		return m.BaseRequest
	}
	return nil
}

func (m *ConnectIotPlatformRequest) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

type ConnectIotPlatformResponse struct {
	BaseResponse         *drivercommon.CommonResponse     `protobuf:"bytes,1,opt,name=baseResponse,proto3" json:"baseResponse,omitempty"`
	Data                 *ConnectIotPlatformResponse_Data `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *ConnectIotPlatformResponse) Reset()         { *m = ConnectIotPlatformResponse{} }
func (m *ConnectIotPlatformResponse) String() string { return proto.CompactTextString(m) }
func (*ConnectIotPlatformResponse) ProtoMessage()    {}
func (*ConnectIotPlatformResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d977e3d1d866a4e5, []int{1}
}

func (m *ConnectIotPlatformResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectIotPlatformResponse.Unmarshal(m, b)
}
func (m *ConnectIotPlatformResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectIotPlatformResponse.Marshal(b, m, deterministic)
}
func (m *ConnectIotPlatformResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectIotPlatformResponse.Merge(m, src)
}
func (m *ConnectIotPlatformResponse) XXX_Size() int {
	return xxx_messageInfo_ConnectIotPlatformResponse.Size(m)
}
func (m *ConnectIotPlatformResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectIotPlatformResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectIotPlatformResponse proto.InternalMessageInfo

func (m *ConnectIotPlatformResponse) GetBaseResponse() *drivercommon.CommonResponse {
	if m != nil {
		return m.BaseResponse
	}
	return nil
}

func (m *ConnectIotPlatformResponse) GetData() *ConnectIotPlatformResponse_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type ConnectIotPlatformResponse_Data struct {
	Status               ConnectStatus `protobuf:"varint,1,opt,name=Status,proto3,enum=driverdevice.ConnectStatus" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ConnectIotPlatformResponse_Data) Reset()         { *m = ConnectIotPlatformResponse_Data{} }
func (m *ConnectIotPlatformResponse_Data) String() string { return proto.CompactTextString(m) }
func (*ConnectIotPlatformResponse_Data) ProtoMessage()    {}
func (*ConnectIotPlatformResponse_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_d977e3d1d866a4e5, []int{1, 0}
}

func (m *ConnectIotPlatformResponse_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectIotPlatformResponse_Data.Unmarshal(m, b)
}
func (m *ConnectIotPlatformResponse_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectIotPlatformResponse_Data.Marshal(b, m, deterministic)
}
func (m *ConnectIotPlatformResponse_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectIotPlatformResponse_Data.Merge(m, src)
}
func (m *ConnectIotPlatformResponse_Data) XXX_Size() int {
	return xxx_messageInfo_ConnectIotPlatformResponse_Data.Size(m)
}
func (m *ConnectIotPlatformResponse_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectIotPlatformResponse_Data.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectIotPlatformResponse_Data proto.InternalMessageInfo

func (m *ConnectIotPlatformResponse_Data) GetStatus() ConnectStatus {
	if m != nil {
		return m.Status
	}
	return ConnectStatus_ONLINE
}

type DisconnectIotPlatformRequest struct {
	BaseRequest          *drivercommon.BaseRequestMessage `protobuf:"bytes,1,opt,name=baseRequest,proto3" json:"baseRequest,omitempty"`
	DeviceId             string                           `protobuf:"bytes,2,opt,name=deviceId,proto3" json:"deviceId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *DisconnectIotPlatformRequest) Reset()         { *m = DisconnectIotPlatformRequest{} }
func (m *DisconnectIotPlatformRequest) String() string { return proto.CompactTextString(m) }
func (*DisconnectIotPlatformRequest) ProtoMessage()    {}
func (*DisconnectIotPlatformRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d977e3d1d866a4e5, []int{2}
}

func (m *DisconnectIotPlatformRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DisconnectIotPlatformRequest.Unmarshal(m, b)
}
func (m *DisconnectIotPlatformRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DisconnectIotPlatformRequest.Marshal(b, m, deterministic)
}
func (m *DisconnectIotPlatformRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DisconnectIotPlatformRequest.Merge(m, src)
}
func (m *DisconnectIotPlatformRequest) XXX_Size() int {
	return xxx_messageInfo_DisconnectIotPlatformRequest.Size(m)
}
func (m *DisconnectIotPlatformRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DisconnectIotPlatformRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DisconnectIotPlatformRequest proto.InternalMessageInfo

func (m *DisconnectIotPlatformRequest) GetBaseRequest() *drivercommon.BaseRequestMessage {
	if m != nil {
		return m.BaseRequest
	}
	return nil
}

func (m *DisconnectIotPlatformRequest) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

type DisconnectIotPlatformResponse struct {
	BaseResponse         *drivercommon.CommonResponse        `protobuf:"bytes,1,opt,name=baseResponse,proto3" json:"baseResponse,omitempty"`
	Data                 *DisconnectIotPlatformResponse_Data `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                            `json:"-"`
	XXX_unrecognized     []byte                              `json:"-"`
	XXX_sizecache        int32                               `json:"-"`
}

func (m *DisconnectIotPlatformResponse) Reset()         { *m = DisconnectIotPlatformResponse{} }
func (m *DisconnectIotPlatformResponse) String() string { return proto.CompactTextString(m) }
func (*DisconnectIotPlatformResponse) ProtoMessage()    {}
func (*DisconnectIotPlatformResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d977e3d1d866a4e5, []int{3}
}

func (m *DisconnectIotPlatformResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DisconnectIotPlatformResponse.Unmarshal(m, b)
}
func (m *DisconnectIotPlatformResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DisconnectIotPlatformResponse.Marshal(b, m, deterministic)
}
func (m *DisconnectIotPlatformResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DisconnectIotPlatformResponse.Merge(m, src)
}
func (m *DisconnectIotPlatformResponse) XXX_Size() int {
	return xxx_messageInfo_DisconnectIotPlatformResponse.Size(m)
}
func (m *DisconnectIotPlatformResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DisconnectIotPlatformResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DisconnectIotPlatformResponse proto.InternalMessageInfo

func (m *DisconnectIotPlatformResponse) GetBaseResponse() *drivercommon.CommonResponse {
	if m != nil {
		return m.BaseResponse
	}
	return nil
}

func (m *DisconnectIotPlatformResponse) GetData() *DisconnectIotPlatformResponse_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type DisconnectIotPlatformResponse_Data struct {
	Status               ConnectStatus `protobuf:"varint,1,opt,name=Status,proto3,enum=driverdevice.ConnectStatus" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *DisconnectIotPlatformResponse_Data) Reset()         { *m = DisconnectIotPlatformResponse_Data{} }
func (m *DisconnectIotPlatformResponse_Data) String() string { return proto.CompactTextString(m) }
func (*DisconnectIotPlatformResponse_Data) ProtoMessage()    {}
func (*DisconnectIotPlatformResponse_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_d977e3d1d866a4e5, []int{3, 0}
}

func (m *DisconnectIotPlatformResponse_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DisconnectIotPlatformResponse_Data.Unmarshal(m, b)
}
func (m *DisconnectIotPlatformResponse_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DisconnectIotPlatformResponse_Data.Marshal(b, m, deterministic)
}
func (m *DisconnectIotPlatformResponse_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DisconnectIotPlatformResponse_Data.Merge(m, src)
}
func (m *DisconnectIotPlatformResponse_Data) XXX_Size() int {
	return xxx_messageInfo_DisconnectIotPlatformResponse_Data.Size(m)
}
func (m *DisconnectIotPlatformResponse_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_DisconnectIotPlatformResponse_Data.DiscardUnknown(m)
}

var xxx_messageInfo_DisconnectIotPlatformResponse_Data proto.InternalMessageInfo

func (m *DisconnectIotPlatformResponse_Data) GetStatus() ConnectStatus {
	if m != nil {
		return m.Status
	}
	return ConnectStatus_ONLINE
}

type QueryDeviceByIdRequest struct {
	BaseRequest          *drivercommon.BaseRequestMessage `protobuf:"bytes,1,opt,name=baseRequest,proto3" json:"baseRequest,omitempty"`
	Id                   string                           `protobuf:"bytes,2,opt,name=Id,proto3" json:"Id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *QueryDeviceByIdRequest) Reset()         { *m = QueryDeviceByIdRequest{} }
func (m *QueryDeviceByIdRequest) String() string { return proto.CompactTextString(m) }
func (*QueryDeviceByIdRequest) ProtoMessage()    {}
func (*QueryDeviceByIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d977e3d1d866a4e5, []int{4}
}

func (m *QueryDeviceByIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryDeviceByIdRequest.Unmarshal(m, b)
}
func (m *QueryDeviceByIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryDeviceByIdRequest.Marshal(b, m, deterministic)
}
func (m *QueryDeviceByIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDeviceByIdRequest.Merge(m, src)
}
func (m *QueryDeviceByIdRequest) XXX_Size() int {
	return xxx_messageInfo_QueryDeviceByIdRequest.Size(m)
}
func (m *QueryDeviceByIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDeviceByIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDeviceByIdRequest proto.InternalMessageInfo

func (m *QueryDeviceByIdRequest) GetBaseRequest() *drivercommon.BaseRequestMessage {
	if m != nil {
		return m.BaseRequest
	}
	return nil
}

func (m *QueryDeviceByIdRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type QueryDeviceByIdResponse struct {
	BaseResponse         *drivercommon.CommonResponse  `protobuf:"bytes,1,opt,name=baseResponse,proto3" json:"baseResponse,omitempty"`
	Data                 *QueryDeviceByIdResponse_Data `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *QueryDeviceByIdResponse) Reset()         { *m = QueryDeviceByIdResponse{} }
func (m *QueryDeviceByIdResponse) String() string { return proto.CompactTextString(m) }
func (*QueryDeviceByIdResponse) ProtoMessage()    {}
func (*QueryDeviceByIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d977e3d1d866a4e5, []int{5}
}

func (m *QueryDeviceByIdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryDeviceByIdResponse.Unmarshal(m, b)
}
func (m *QueryDeviceByIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryDeviceByIdResponse.Marshal(b, m, deterministic)
}
func (m *QueryDeviceByIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDeviceByIdResponse.Merge(m, src)
}
func (m *QueryDeviceByIdResponse) XXX_Size() int {
	return xxx_messageInfo_QueryDeviceByIdResponse.Size(m)
}
func (m *QueryDeviceByIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDeviceByIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDeviceByIdResponse proto.InternalMessageInfo

func (m *QueryDeviceByIdResponse) GetBaseResponse() *drivercommon.CommonResponse {
	if m != nil {
		return m.BaseResponse
	}
	return nil
}

func (m *QueryDeviceByIdResponse) GetData() *QueryDeviceByIdResponse_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type QueryDeviceByIdResponse_Data struct {
	Device               *Device  `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryDeviceByIdResponse_Data) Reset()         { *m = QueryDeviceByIdResponse_Data{} }
func (m *QueryDeviceByIdResponse_Data) String() string { return proto.CompactTextString(m) }
func (*QueryDeviceByIdResponse_Data) ProtoMessage()    {}
func (*QueryDeviceByIdResponse_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_d977e3d1d866a4e5, []int{5, 0}
}

func (m *QueryDeviceByIdResponse_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryDeviceByIdResponse_Data.Unmarshal(m, b)
}
func (m *QueryDeviceByIdResponse_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryDeviceByIdResponse_Data.Marshal(b, m, deterministic)
}
func (m *QueryDeviceByIdResponse_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDeviceByIdResponse_Data.Merge(m, src)
}
func (m *QueryDeviceByIdResponse_Data) XXX_Size() int {
	return xxx_messageInfo_QueryDeviceByIdResponse_Data.Size(m)
}
func (m *QueryDeviceByIdResponse_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDeviceByIdResponse_Data.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDeviceByIdResponse_Data proto.InternalMessageInfo

func (m *QueryDeviceByIdResponse_Data) GetDevice() *Device {
	if m != nil {
		return m.Device
	}
	return nil
}

type Device struct {
	Id                   string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string            `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ProductId            string            `protobuf:"bytes,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	DeviceSn             string            `protobuf:"bytes,4,opt,name=device_sn,json=deviceSn,proto3" json:"device_sn,omitempty"`
	Status               DeviceStatus      `protobuf:"varint,5,opt,name=status,proto3,enum=driverdevice.DeviceStatus" json:"status,omitempty"`
	Secret               string            `protobuf:"bytes,6,opt,name=secret,proto3" json:"secret,omitempty"`
	Ip                   string            `protobuf:"bytes,7,opt,name=ip,proto3" json:"ip,omitempty"`
	Port                 string            `protobuf:"bytes,8,opt,name=port,proto3" json:"port,omitempty"`
	Lat                  string            `protobuf:"bytes,9,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon                  string            `protobuf:"bytes,10,opt,name=lon,proto3" json:"lon,omitempty"`
	Location             string            `protobuf:"bytes,11,opt,name=location,proto3" json:"location,omitempty"`
	ParentId             string            `protobuf:"bytes,12,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Manufacturer         string            `protobuf:"bytes,13,opt,name=manufacturer,proto3" json:"manufacturer,omitempty"`
	Model                string            `protobuf:"bytes,14,opt,name=model,proto3" json:"model,omitempty"`
	External             map[string]string `protobuf:"bytes,15,rep,name=External,proto3" json:"External,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Description          string            `protobuf:"bytes,16,opt,name=description,proto3" json:"description,omitempty"`
	Transport            string            `protobuf:"bytes,17,opt,name=transport,proto3" json:"transport,omitempty"`
	SlaveId              string            `protobuf:"bytes,18,opt,name=slave_id,json=slaveId,proto3" json:"slave_id,omitempty"`
	Period               string            `protobuf:"bytes,19,opt,name=period,proto3" json:"period,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Device) Reset()         { *m = Device{} }
func (m *Device) String() string { return proto.CompactTextString(m) }
func (*Device) ProtoMessage()    {}
func (*Device) Descriptor() ([]byte, []int) {
	return fileDescriptor_d977e3d1d866a4e5, []int{6}
}

func (m *Device) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Device.Unmarshal(m, b)
}
func (m *Device) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Device.Marshal(b, m, deterministic)
}
func (m *Device) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Device.Merge(m, src)
}
func (m *Device) XXX_Size() int {
	return xxx_messageInfo_Device.Size(m)
}
func (m *Device) XXX_DiscardUnknown() {
	xxx_messageInfo_Device.DiscardUnknown(m)
}

var xxx_messageInfo_Device proto.InternalMessageInfo

func (m *Device) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Device) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Device) GetProductId() string {
	if m != nil {
		return m.ProductId
	}
	return ""
}

func (m *Device) GetDeviceSn() string {
	if m != nil {
		return m.DeviceSn
	}
	return ""
}

func (m *Device) GetStatus() DeviceStatus {
	if m != nil {
		return m.Status
	}
	return DeviceStatus_UnKnowStatus
}

func (m *Device) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

func (m *Device) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *Device) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

func (m *Device) GetLat() string {
	if m != nil {
		return m.Lat
	}
	return ""
}

func (m *Device) GetLon() string {
	if m != nil {
		return m.Lon
	}
	return ""
}

func (m *Device) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *Device) GetParentId() string {
	if m != nil {
		return m.ParentId
	}
	return ""
}

func (m *Device) GetManufacturer() string {
	if m != nil {
		return m.Manufacturer
	}
	return ""
}

func (m *Device) GetModel() string {
	if m != nil {
		return m.Model
	}
	return ""
}

func (m *Device) GetExternal() map[string]string {
	if m != nil {
		return m.External
	}
	return nil
}

func (m *Device) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Device) GetTransport() string {
	if m != nil {
		return m.Transport
	}
	return ""
}

func (m *Device) GetSlaveId() string {
	if m != nil {
		return m.SlaveId
	}
	return ""
}

func (m *Device) GetPeriod() string {
	if m != nil {
		return m.Period
	}
	return ""
}

type QueryDeviceListRequest struct {
	BaseRequest          *drivercommon.BaseRequestMessage `protobuf:"bytes,1,opt,name=baseRequest,proto3" json:"baseRequest,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *QueryDeviceListRequest) Reset()         { *m = QueryDeviceListRequest{} }
func (m *QueryDeviceListRequest) String() string { return proto.CompactTextString(m) }
func (*QueryDeviceListRequest) ProtoMessage()    {}
func (*QueryDeviceListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d977e3d1d866a4e5, []int{7}
}

func (m *QueryDeviceListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryDeviceListRequest.Unmarshal(m, b)
}
func (m *QueryDeviceListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryDeviceListRequest.Marshal(b, m, deterministic)
}
func (m *QueryDeviceListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDeviceListRequest.Merge(m, src)
}
func (m *QueryDeviceListRequest) XXX_Size() int {
	return xxx_messageInfo_QueryDeviceListRequest.Size(m)
}
func (m *QueryDeviceListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDeviceListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDeviceListRequest proto.InternalMessageInfo

func (m *QueryDeviceListRequest) GetBaseRequest() *drivercommon.BaseRequestMessage {
	if m != nil {
		return m.BaseRequest
	}
	return nil
}

type QueryDeviceListResponse struct {
	BaseResponse         *drivercommon.CommonResponse  `protobuf:"bytes,1,opt,name=baseResponse,proto3" json:"baseResponse,omitempty"`
	Data                 *QueryDeviceListResponse_Data `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *QueryDeviceListResponse) Reset()         { *m = QueryDeviceListResponse{} }
func (m *QueryDeviceListResponse) String() string { return proto.CompactTextString(m) }
func (*QueryDeviceListResponse) ProtoMessage()    {}
func (*QueryDeviceListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d977e3d1d866a4e5, []int{8}
}

func (m *QueryDeviceListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryDeviceListResponse.Unmarshal(m, b)
}
func (m *QueryDeviceListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryDeviceListResponse.Marshal(b, m, deterministic)
}
func (m *QueryDeviceListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDeviceListResponse.Merge(m, src)
}
func (m *QueryDeviceListResponse) XXX_Size() int {
	return xxx_messageInfo_QueryDeviceListResponse.Size(m)
}
func (m *QueryDeviceListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDeviceListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDeviceListResponse proto.InternalMessageInfo

func (m *QueryDeviceListResponse) GetBaseResponse() *drivercommon.CommonResponse {
	if m != nil {
		return m.BaseResponse
	}
	return nil
}

func (m *QueryDeviceListResponse) GetData() *QueryDeviceListResponse_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type QueryDeviceListResponse_Data struct {
	Total                uint32    `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Devices              []*Device `protobuf:"bytes,2,rep,name=devices,proto3" json:"devices,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *QueryDeviceListResponse_Data) Reset()         { *m = QueryDeviceListResponse_Data{} }
func (m *QueryDeviceListResponse_Data) String() string { return proto.CompactTextString(m) }
func (*QueryDeviceListResponse_Data) ProtoMessage()    {}
func (*QueryDeviceListResponse_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_d977e3d1d866a4e5, []int{8, 0}
}

func (m *QueryDeviceListResponse_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryDeviceListResponse_Data.Unmarshal(m, b)
}
func (m *QueryDeviceListResponse_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryDeviceListResponse_Data.Marshal(b, m, deterministic)
}
func (m *QueryDeviceListResponse_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDeviceListResponse_Data.Merge(m, src)
}
func (m *QueryDeviceListResponse_Data) XXX_Size() int {
	return xxx_messageInfo_QueryDeviceListResponse_Data.Size(m)
}
func (m *QueryDeviceListResponse_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDeviceListResponse_Data.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDeviceListResponse_Data proto.InternalMessageInfo

func (m *QueryDeviceListResponse_Data) GetTotal() uint32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *QueryDeviceListResponse_Data) GetDevices() []*Device {
	if m != nil {
		return m.Devices
	}
	return nil
}

type AddDevice struct {
	Name                 string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ProductId            string            `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	DeviceSn             string            `protobuf:"bytes,3,opt,name=device_sn,json=deviceSn,proto3" json:"device_sn,omitempty"`
	Status               DeviceStatus      `protobuf:"varint,4,opt,name=status,proto3,enum=driverdevice.DeviceStatus" json:"status,omitempty"`
	Ip                   string            `protobuf:"bytes,5,opt,name=ip,proto3" json:"ip,omitempty"`
	Port                 string            `protobuf:"bytes,6,opt,name=port,proto3" json:"port,omitempty"`
	Lat                  string            `protobuf:"bytes,7,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon                  string            `protobuf:"bytes,8,opt,name=lon,proto3" json:"lon,omitempty"`
	Location             string            `protobuf:"bytes,9,opt,name=location,proto3" json:"location,omitempty"`
	ParentId             string            `protobuf:"bytes,10,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Manufacturer         string            `protobuf:"bytes,11,opt,name=manufacturer,proto3" json:"manufacturer,omitempty"`
	Model                string            `protobuf:"bytes,12,opt,name=model,proto3" json:"model,omitempty"`
	External             map[string]string `protobuf:"bytes,13,rep,name=External,proto3" json:"External,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Description          string            `protobuf:"bytes,14,opt,name=description,proto3" json:"description,omitempty"`
	Transport            string            `protobuf:"bytes,15,opt,name=transport,proto3" json:"transport,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *AddDevice) Reset()         { *m = AddDevice{} }
func (m *AddDevice) String() string { return proto.CompactTextString(m) }
func (*AddDevice) ProtoMessage()    {}
func (*AddDevice) Descriptor() ([]byte, []int) {
	return fileDescriptor_d977e3d1d866a4e5, []int{9}
}

func (m *AddDevice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddDevice.Unmarshal(m, b)
}
func (m *AddDevice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddDevice.Marshal(b, m, deterministic)
}
func (m *AddDevice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddDevice.Merge(m, src)
}
func (m *AddDevice) XXX_Size() int {
	return xxx_messageInfo_AddDevice.Size(m)
}
func (m *AddDevice) XXX_DiscardUnknown() {
	xxx_messageInfo_AddDevice.DiscardUnknown(m)
}

var xxx_messageInfo_AddDevice proto.InternalMessageInfo

func (m *AddDevice) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AddDevice) GetProductId() string {
	if m != nil {
		return m.ProductId
	}
	return ""
}

func (m *AddDevice) GetDeviceSn() string {
	if m != nil {
		return m.DeviceSn
	}
	return ""
}

func (m *AddDevice) GetStatus() DeviceStatus {
	if m != nil {
		return m.Status
	}
	return DeviceStatus_UnKnowStatus
}

func (m *AddDevice) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *AddDevice) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

func (m *AddDevice) GetLat() string {
	if m != nil {
		return m.Lat
	}
	return ""
}

func (m *AddDevice) GetLon() string {
	if m != nil {
		return m.Lon
	}
	return ""
}

func (m *AddDevice) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *AddDevice) GetParentId() string {
	if m != nil {
		return m.ParentId
	}
	return ""
}

func (m *AddDevice) GetManufacturer() string {
	if m != nil {
		return m.Manufacturer
	}
	return ""
}

func (m *AddDevice) GetModel() string {
	if m != nil {
		return m.Model
	}
	return ""
}

func (m *AddDevice) GetExternal() map[string]string {
	if m != nil {
		return m.External
	}
	return nil
}

func (m *AddDevice) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *AddDevice) GetTransport() string {
	if m != nil {
		return m.Transport
	}
	return ""
}

type UpdateDevice struct {
	Id                   string            `protobuf:"bytes,16,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ProductId            string            `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	DeviceSn             string            `protobuf:"bytes,3,opt,name=device_sn,json=deviceSn,proto3" json:"device_sn,omitempty"`
	Status               DeviceStatus      `protobuf:"varint,4,opt,name=status,proto3,enum=driverdevice.DeviceStatus" json:"status,omitempty"`
	Ip                   string            `protobuf:"bytes,5,opt,name=ip,proto3" json:"ip,omitempty"`
	Port                 string            `protobuf:"bytes,6,opt,name=port,proto3" json:"port,omitempty"`
	Lat                  string            `protobuf:"bytes,7,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon                  string            `protobuf:"bytes,8,opt,name=lon,proto3" json:"lon,omitempty"`
	Location             string            `protobuf:"bytes,9,opt,name=location,proto3" json:"location,omitempty"`
	ParentId             string            `protobuf:"bytes,10,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Manufacturer         string            `protobuf:"bytes,11,opt,name=manufacturer,proto3" json:"manufacturer,omitempty"`
	Model                string            `protobuf:"bytes,12,opt,name=model,proto3" json:"model,omitempty"`
	External             map[string]string `protobuf:"bytes,13,rep,name=External,proto3" json:"External,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Description          string            `protobuf:"bytes,14,opt,name=description,proto3" json:"description,omitempty"`
	Transport            string            `protobuf:"bytes,15,opt,name=transport,proto3" json:"transport,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *UpdateDevice) Reset()         { *m = UpdateDevice{} }
func (m *UpdateDevice) String() string { return proto.CompactTextString(m) }
func (*UpdateDevice) ProtoMessage()    {}
func (*UpdateDevice) Descriptor() ([]byte, []int) {
	return fileDescriptor_d977e3d1d866a4e5, []int{10}
}

func (m *UpdateDevice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateDevice.Unmarshal(m, b)
}
func (m *UpdateDevice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateDevice.Marshal(b, m, deterministic)
}
func (m *UpdateDevice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateDevice.Merge(m, src)
}
func (m *UpdateDevice) XXX_Size() int {
	return xxx_messageInfo_UpdateDevice.Size(m)
}
func (m *UpdateDevice) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateDevice.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateDevice proto.InternalMessageInfo

func (m *UpdateDevice) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateDevice) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateDevice) GetProductId() string {
	if m != nil {
		return m.ProductId
	}
	return ""
}

func (m *UpdateDevice) GetDeviceSn() string {
	if m != nil {
		return m.DeviceSn
	}
	return ""
}

func (m *UpdateDevice) GetStatus() DeviceStatus {
	if m != nil {
		return m.Status
	}
	return DeviceStatus_UnKnowStatus
}

func (m *UpdateDevice) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *UpdateDevice) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

func (m *UpdateDevice) GetLat() string {
	if m != nil {
		return m.Lat
	}
	return ""
}

func (m *UpdateDevice) GetLon() string {
	if m != nil {
		return m.Lon
	}
	return ""
}

func (m *UpdateDevice) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *UpdateDevice) GetParentId() string {
	if m != nil {
		return m.ParentId
	}
	return ""
}

func (m *UpdateDevice) GetManufacturer() string {
	if m != nil {
		return m.Manufacturer
	}
	return ""
}

func (m *UpdateDevice) GetModel() string {
	if m != nil {
		return m.Model
	}
	return ""
}

func (m *UpdateDevice) GetExternal() map[string]string {
	if m != nil {
		return m.External
	}
	return nil
}

func (m *UpdateDevice) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *UpdateDevice) GetTransport() string {
	if m != nil {
		return m.Transport
	}
	return ""
}

type CreateDeviceRequest struct {
	BaseRequest          *drivercommon.BaseRequestMessage `protobuf:"bytes,1,opt,name=baseRequest,proto3" json:"baseRequest,omitempty"`
	Device               *AddDevice                       `protobuf:"bytes,2,opt,name=device,proto3" json:"device,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *CreateDeviceRequest) Reset()         { *m = CreateDeviceRequest{} }
func (m *CreateDeviceRequest) String() string { return proto.CompactTextString(m) }
func (*CreateDeviceRequest) ProtoMessage()    {}
func (*CreateDeviceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d977e3d1d866a4e5, []int{11}
}

func (m *CreateDeviceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateDeviceRequest.Unmarshal(m, b)
}
func (m *CreateDeviceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateDeviceRequest.Marshal(b, m, deterministic)
}
func (m *CreateDeviceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateDeviceRequest.Merge(m, src)
}
func (m *CreateDeviceRequest) XXX_Size() int {
	return xxx_messageInfo_CreateDeviceRequest.Size(m)
}
func (m *CreateDeviceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateDeviceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateDeviceRequest proto.InternalMessageInfo

func (m *CreateDeviceRequest) GetBaseRequest() *drivercommon.BaseRequestMessage {
	if m != nil {
		return m.BaseRequest
	}
	return nil
}

func (m *CreateDeviceRequest) GetDevice() *AddDevice {
	if m != nil {
		return m.Device
	}
	return nil
}

type CreateDeviceRequestResponse struct {
	Data                 *CreateDeviceRequestResponse_Data `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	BaseResponse         *drivercommon.CommonResponse      `protobuf:"bytes,1,opt,name=baseResponse,proto3" json:"baseResponse,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *CreateDeviceRequestResponse) Reset()         { *m = CreateDeviceRequestResponse{} }
func (m *CreateDeviceRequestResponse) String() string { return proto.CompactTextString(m) }
func (*CreateDeviceRequestResponse) ProtoMessage()    {}
func (*CreateDeviceRequestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d977e3d1d866a4e5, []int{12}
}

func (m *CreateDeviceRequestResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateDeviceRequestResponse.Unmarshal(m, b)
}
func (m *CreateDeviceRequestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateDeviceRequestResponse.Marshal(b, m, deterministic)
}
func (m *CreateDeviceRequestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateDeviceRequestResponse.Merge(m, src)
}
func (m *CreateDeviceRequestResponse) XXX_Size() int {
	return xxx_messageInfo_CreateDeviceRequestResponse.Size(m)
}
func (m *CreateDeviceRequestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateDeviceRequestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateDeviceRequestResponse proto.InternalMessageInfo

func (m *CreateDeviceRequestResponse) GetData() *CreateDeviceRequestResponse_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *CreateDeviceRequestResponse) GetBaseResponse() *drivercommon.CommonResponse {
	if m != nil {
		return m.BaseResponse
	}
	return nil
}

type CreateDeviceRequestResponse_Data struct {
	Devices              *Device  `protobuf:"bytes,2,opt,name=devices,proto3" json:"devices,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateDeviceRequestResponse_Data) Reset()         { *m = CreateDeviceRequestResponse_Data{} }
func (m *CreateDeviceRequestResponse_Data) String() string { return proto.CompactTextString(m) }
func (*CreateDeviceRequestResponse_Data) ProtoMessage()    {}
func (*CreateDeviceRequestResponse_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_d977e3d1d866a4e5, []int{12, 0}
}

func (m *CreateDeviceRequestResponse_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateDeviceRequestResponse_Data.Unmarshal(m, b)
}
func (m *CreateDeviceRequestResponse_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateDeviceRequestResponse_Data.Marshal(b, m, deterministic)
}
func (m *CreateDeviceRequestResponse_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateDeviceRequestResponse_Data.Merge(m, src)
}
func (m *CreateDeviceRequestResponse_Data) XXX_Size() int {
	return xxx_messageInfo_CreateDeviceRequestResponse_Data.Size(m)
}
func (m *CreateDeviceRequestResponse_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateDeviceRequestResponse_Data.DiscardUnknown(m)
}

var xxx_messageInfo_CreateDeviceRequestResponse_Data proto.InternalMessageInfo

func (m *CreateDeviceRequestResponse_Data) GetDevices() *Device {
	if m != nil {
		return m.Devices
	}
	return nil
}

type UpdateDeviceRequestResponse struct {
	Data                 *UpdateDeviceRequestResponse_Data `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	BaseResponse         *drivercommon.CommonResponse      `protobuf:"bytes,1,opt,name=baseResponse,proto3" json:"baseResponse,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *UpdateDeviceRequestResponse) Reset()         { *m = UpdateDeviceRequestResponse{} }
func (m *UpdateDeviceRequestResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateDeviceRequestResponse) ProtoMessage()    {}
func (*UpdateDeviceRequestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d977e3d1d866a4e5, []int{13}
}

func (m *UpdateDeviceRequestResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateDeviceRequestResponse.Unmarshal(m, b)
}
func (m *UpdateDeviceRequestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateDeviceRequestResponse.Marshal(b, m, deterministic)
}
func (m *UpdateDeviceRequestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateDeviceRequestResponse.Merge(m, src)
}
func (m *UpdateDeviceRequestResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateDeviceRequestResponse.Size(m)
}
func (m *UpdateDeviceRequestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateDeviceRequestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateDeviceRequestResponse proto.InternalMessageInfo

func (m *UpdateDeviceRequestResponse) GetData() *UpdateDeviceRequestResponse_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *UpdateDeviceRequestResponse) GetBaseResponse() *drivercommon.CommonResponse {
	if m != nil {
		return m.BaseResponse
	}
	return nil
}

type UpdateDeviceRequestResponse_Data struct {
	Devices              *Device  `protobuf:"bytes,2,opt,name=devices,proto3" json:"devices,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateDeviceRequestResponse_Data) Reset()         { *m = UpdateDeviceRequestResponse_Data{} }
func (m *UpdateDeviceRequestResponse_Data) String() string { return proto.CompactTextString(m) }
func (*UpdateDeviceRequestResponse_Data) ProtoMessage()    {}
func (*UpdateDeviceRequestResponse_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_d977e3d1d866a4e5, []int{13, 0}
}

func (m *UpdateDeviceRequestResponse_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateDeviceRequestResponse_Data.Unmarshal(m, b)
}
func (m *UpdateDeviceRequestResponse_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateDeviceRequestResponse_Data.Marshal(b, m, deterministic)
}
func (m *UpdateDeviceRequestResponse_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateDeviceRequestResponse_Data.Merge(m, src)
}
func (m *UpdateDeviceRequestResponse_Data) XXX_Size() int {
	return xxx_messageInfo_UpdateDeviceRequestResponse_Data.Size(m)
}
func (m *UpdateDeviceRequestResponse_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateDeviceRequestResponse_Data.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateDeviceRequestResponse_Data proto.InternalMessageInfo

func (m *UpdateDeviceRequestResponse_Data) GetDevices() *Device {
	if m != nil {
		return m.Devices
	}
	return nil
}

type UpdateDeviceRequest struct {
	BaseRequest          *drivercommon.BaseRequestMessage `protobuf:"bytes,1,opt,name=baseRequest,proto3" json:"baseRequest,omitempty"`
	Device               *UpdateDevice                    `protobuf:"bytes,2,opt,name=device,proto3" json:"device,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *UpdateDeviceRequest) Reset()         { *m = UpdateDeviceRequest{} }
func (m *UpdateDeviceRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateDeviceRequest) ProtoMessage()    {}
func (*UpdateDeviceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d977e3d1d866a4e5, []int{14}
}

func (m *UpdateDeviceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateDeviceRequest.Unmarshal(m, b)
}
func (m *UpdateDeviceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateDeviceRequest.Marshal(b, m, deterministic)
}
func (m *UpdateDeviceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateDeviceRequest.Merge(m, src)
}
func (m *UpdateDeviceRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateDeviceRequest.Size(m)
}
func (m *UpdateDeviceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateDeviceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateDeviceRequest proto.InternalMessageInfo

func (m *UpdateDeviceRequest) GetBaseRequest() *drivercommon.BaseRequestMessage {
	if m != nil {
		return m.BaseRequest
	}
	return nil
}

func (m *UpdateDeviceRequest) GetDevice() *UpdateDevice {
	if m != nil {
		return m.Device
	}
	return nil
}

type CreateDeviceAndConnectRequest struct {
	Device               *AddDevice `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *CreateDeviceAndConnectRequest) Reset()         { *m = CreateDeviceAndConnectRequest{} }
func (m *CreateDeviceAndConnectRequest) String() string { return proto.CompactTextString(m) }
func (*CreateDeviceAndConnectRequest) ProtoMessage()    {}
func (*CreateDeviceAndConnectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d977e3d1d866a4e5, []int{15}
}

func (m *CreateDeviceAndConnectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateDeviceAndConnectRequest.Unmarshal(m, b)
}
func (m *CreateDeviceAndConnectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateDeviceAndConnectRequest.Marshal(b, m, deterministic)
}
func (m *CreateDeviceAndConnectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateDeviceAndConnectRequest.Merge(m, src)
}
func (m *CreateDeviceAndConnectRequest) XXX_Size() int {
	return xxx_messageInfo_CreateDeviceAndConnectRequest.Size(m)
}
func (m *CreateDeviceAndConnectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateDeviceAndConnectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateDeviceAndConnectRequest proto.InternalMessageInfo

func (m *CreateDeviceAndConnectRequest) GetDevice() *AddDevice {
	if m != nil {
		return m.Device
	}
	return nil
}

type CreateDeviceAndConnectRequestResponse struct {
	BaseResponse         *drivercommon.CommonResponse                `protobuf:"bytes,1,opt,name=baseResponse,proto3" json:"baseResponse,omitempty"`
	Data                 *CreateDeviceAndConnectRequestResponse_Data `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                    `json:"-"`
	XXX_unrecognized     []byte                                      `json:"-"`
	XXX_sizecache        int32                                       `json:"-"`
}

func (m *CreateDeviceAndConnectRequestResponse) Reset()         { *m = CreateDeviceAndConnectRequestResponse{} }
func (m *CreateDeviceAndConnectRequestResponse) String() string { return proto.CompactTextString(m) }
func (*CreateDeviceAndConnectRequestResponse) ProtoMessage()    {}
func (*CreateDeviceAndConnectRequestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d977e3d1d866a4e5, []int{16}
}

func (m *CreateDeviceAndConnectRequestResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateDeviceAndConnectRequestResponse.Unmarshal(m, b)
}
func (m *CreateDeviceAndConnectRequestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateDeviceAndConnectRequestResponse.Marshal(b, m, deterministic)
}
func (m *CreateDeviceAndConnectRequestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateDeviceAndConnectRequestResponse.Merge(m, src)
}
func (m *CreateDeviceAndConnectRequestResponse) XXX_Size() int {
	return xxx_messageInfo_CreateDeviceAndConnectRequestResponse.Size(m)
}
func (m *CreateDeviceAndConnectRequestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateDeviceAndConnectRequestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateDeviceAndConnectRequestResponse proto.InternalMessageInfo

func (m *CreateDeviceAndConnectRequestResponse) GetBaseResponse() *drivercommon.CommonResponse {
	if m != nil {
		return m.BaseResponse
	}
	return nil
}

func (m *CreateDeviceAndConnectRequestResponse) GetData() *CreateDeviceAndConnectRequestResponse_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type CreateDeviceAndConnectRequestResponse_Data struct {
	Devices              *Device  `protobuf:"bytes,1,opt,name=devices,proto3" json:"devices,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateDeviceAndConnectRequestResponse_Data) Reset() {
	*m = CreateDeviceAndConnectRequestResponse_Data{}
}
func (m *CreateDeviceAndConnectRequestResponse_Data) String() string {
	return proto.CompactTextString(m)
}
func (*CreateDeviceAndConnectRequestResponse_Data) ProtoMessage() {}
func (*CreateDeviceAndConnectRequestResponse_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_d977e3d1d866a4e5, []int{16, 0}
}

func (m *CreateDeviceAndConnectRequestResponse_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateDeviceAndConnectRequestResponse_Data.Unmarshal(m, b)
}
func (m *CreateDeviceAndConnectRequestResponse_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateDeviceAndConnectRequestResponse_Data.Marshal(b, m, deterministic)
}
func (m *CreateDeviceAndConnectRequestResponse_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateDeviceAndConnectRequestResponse_Data.Merge(m, src)
}
func (m *CreateDeviceAndConnectRequestResponse_Data) XXX_Size() int {
	return xxx_messageInfo_CreateDeviceAndConnectRequestResponse_Data.Size(m)
}
func (m *CreateDeviceAndConnectRequestResponse_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateDeviceAndConnectRequestResponse_Data.DiscardUnknown(m)
}

var xxx_messageInfo_CreateDeviceAndConnectRequestResponse_Data proto.InternalMessageInfo

func (m *CreateDeviceAndConnectRequestResponse_Data) GetDevices() *Device {
	if m != nil {
		return m.Devices
	}
	return nil
}

type DeleteDeviceRequest struct {
	BaseRequest          *drivercommon.BaseRequestMessage `protobuf:"bytes,1,opt,name=baseRequest,proto3" json:"baseRequest,omitempty"`
	DeviceId             string                           `protobuf:"bytes,2,opt,name=deviceId,proto3" json:"deviceId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *DeleteDeviceRequest) Reset()         { *m = DeleteDeviceRequest{} }
func (m *DeleteDeviceRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteDeviceRequest) ProtoMessage()    {}
func (*DeleteDeviceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d977e3d1d866a4e5, []int{17}
}

func (m *DeleteDeviceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteDeviceRequest.Unmarshal(m, b)
}
func (m *DeleteDeviceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteDeviceRequest.Marshal(b, m, deterministic)
}
func (m *DeleteDeviceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteDeviceRequest.Merge(m, src)
}
func (m *DeleteDeviceRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteDeviceRequest.Size(m)
}
func (m *DeleteDeviceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteDeviceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteDeviceRequest proto.InternalMessageInfo

func (m *DeleteDeviceRequest) GetBaseRequest() *drivercommon.BaseRequestMessage {
	if m != nil {
		return m.BaseRequest
	}
	return nil
}

func (m *DeleteDeviceRequest) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

type DeleteDeviceResponse struct {
	BaseResponse         *drivercommon.CommonResponse `protobuf:"bytes,1,opt,name=baseResponse,proto3" json:"baseResponse,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *DeleteDeviceResponse) Reset()         { *m = DeleteDeviceResponse{} }
func (m *DeleteDeviceResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteDeviceResponse) ProtoMessage()    {}
func (*DeleteDeviceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d977e3d1d866a4e5, []int{18}
}

func (m *DeleteDeviceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteDeviceResponse.Unmarshal(m, b)
}
func (m *DeleteDeviceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteDeviceResponse.Marshal(b, m, deterministic)
}
func (m *DeleteDeviceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteDeviceResponse.Merge(m, src)
}
func (m *DeleteDeviceResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteDeviceResponse.Size(m)
}
func (m *DeleteDeviceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteDeviceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteDeviceResponse proto.InternalMessageInfo

func (m *DeleteDeviceResponse) GetBaseResponse() *drivercommon.CommonResponse {
	if m != nil {
		return m.BaseResponse
	}
	return nil
}

type GetDeviceConnectStatusRequest struct {
	BaseRequest          *drivercommon.BaseRequestMessage `protobuf:"bytes,1,opt,name=baseRequest,proto3" json:"baseRequest,omitempty"`
	DeviceId             string                           `protobuf:"bytes,2,opt,name=deviceId,proto3" json:"deviceId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *GetDeviceConnectStatusRequest) Reset()         { *m = GetDeviceConnectStatusRequest{} }
func (m *GetDeviceConnectStatusRequest) String() string { return proto.CompactTextString(m) }
func (*GetDeviceConnectStatusRequest) ProtoMessage()    {}
func (*GetDeviceConnectStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d977e3d1d866a4e5, []int{19}
}

func (m *GetDeviceConnectStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDeviceConnectStatusRequest.Unmarshal(m, b)
}
func (m *GetDeviceConnectStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDeviceConnectStatusRequest.Marshal(b, m, deterministic)
}
func (m *GetDeviceConnectStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDeviceConnectStatusRequest.Merge(m, src)
}
func (m *GetDeviceConnectStatusRequest) XXX_Size() int {
	return xxx_messageInfo_GetDeviceConnectStatusRequest.Size(m)
}
func (m *GetDeviceConnectStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDeviceConnectStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDeviceConnectStatusRequest proto.InternalMessageInfo

func (m *GetDeviceConnectStatusRequest) GetBaseRequest() *drivercommon.BaseRequestMessage {
	if m != nil {
		return m.BaseRequest
	}
	return nil
}

func (m *GetDeviceConnectStatusRequest) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

type GetDeviceConnectStatusResponse struct {
	Data                 *GetDeviceConnectStatusResponse_Data `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	BaseResponse         *drivercommon.CommonResponse         `protobuf:"bytes,1,opt,name=baseResponse,proto3" json:"baseResponse,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                             `json:"-"`
	XXX_unrecognized     []byte                               `json:"-"`
	XXX_sizecache        int32                                `json:"-"`
}

func (m *GetDeviceConnectStatusResponse) Reset()         { *m = GetDeviceConnectStatusResponse{} }
func (m *GetDeviceConnectStatusResponse) String() string { return proto.CompactTextString(m) }
func (*GetDeviceConnectStatusResponse) ProtoMessage()    {}
func (*GetDeviceConnectStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d977e3d1d866a4e5, []int{20}
}

func (m *GetDeviceConnectStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDeviceConnectStatusResponse.Unmarshal(m, b)
}
func (m *GetDeviceConnectStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDeviceConnectStatusResponse.Marshal(b, m, deterministic)
}
func (m *GetDeviceConnectStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDeviceConnectStatusResponse.Merge(m, src)
}
func (m *GetDeviceConnectStatusResponse) XXX_Size() int {
	return xxx_messageInfo_GetDeviceConnectStatusResponse.Size(m)
}
func (m *GetDeviceConnectStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDeviceConnectStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDeviceConnectStatusResponse proto.InternalMessageInfo

func (m *GetDeviceConnectStatusResponse) GetData() *GetDeviceConnectStatusResponse_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *GetDeviceConnectStatusResponse) GetBaseResponse() *drivercommon.CommonResponse {
	if m != nil {
		return m.BaseResponse
	}
	return nil
}

type GetDeviceConnectStatusResponse_Data struct {
	Status               ConnectStatus `protobuf:"varint,1,opt,name=Status,proto3,enum=driverdevice.ConnectStatus" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetDeviceConnectStatusResponse_Data) Reset()         { *m = GetDeviceConnectStatusResponse_Data{} }
func (m *GetDeviceConnectStatusResponse_Data) String() string { return proto.CompactTextString(m) }
func (*GetDeviceConnectStatusResponse_Data) ProtoMessage()    {}
func (*GetDeviceConnectStatusResponse_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_d977e3d1d866a4e5, []int{20, 0}
}

func (m *GetDeviceConnectStatusResponse_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDeviceConnectStatusResponse_Data.Unmarshal(m, b)
}
func (m *GetDeviceConnectStatusResponse_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDeviceConnectStatusResponse_Data.Marshal(b, m, deterministic)
}
func (m *GetDeviceConnectStatusResponse_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDeviceConnectStatusResponse_Data.Merge(m, src)
}
func (m *GetDeviceConnectStatusResponse_Data) XXX_Size() int {
	return xxx_messageInfo_GetDeviceConnectStatusResponse_Data.Size(m)
}
func (m *GetDeviceConnectStatusResponse_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDeviceConnectStatusResponse_Data.DiscardUnknown(m)
}

var xxx_messageInfo_GetDeviceConnectStatusResponse_Data proto.InternalMessageInfo

func (m *GetDeviceConnectStatusResponse_Data) GetStatus() ConnectStatus {
	if m != nil {
		return m.Status
	}
	return ConnectStatus_ONLINE
}

func init() {
	proto.RegisterEnum("driverdevice.DeviceStatus", DeviceStatus_name, DeviceStatus_value)
	proto.RegisterEnum("driverdevice.ConnectStatus", ConnectStatus_name, ConnectStatus_value)
	proto.RegisterType((*ConnectIotPlatformRequest)(nil), "driverdevice.ConnectIotPlatformRequest")
	proto.RegisterType((*ConnectIotPlatformResponse)(nil), "driverdevice.ConnectIotPlatformResponse")
	proto.RegisterType((*ConnectIotPlatformResponse_Data)(nil), "driverdevice.ConnectIotPlatformResponse.Data")
	proto.RegisterType((*DisconnectIotPlatformRequest)(nil), "driverdevice.DisconnectIotPlatformRequest")
	proto.RegisterType((*DisconnectIotPlatformResponse)(nil), "driverdevice.DisconnectIotPlatformResponse")
	proto.RegisterType((*DisconnectIotPlatformResponse_Data)(nil), "driverdevice.DisconnectIotPlatformResponse.Data")
	proto.RegisterType((*QueryDeviceByIdRequest)(nil), "driverdevice.QueryDeviceByIdRequest")
	proto.RegisterType((*QueryDeviceByIdResponse)(nil), "driverdevice.QueryDeviceByIdResponse")
	proto.RegisterType((*QueryDeviceByIdResponse_Data)(nil), "driverdevice.QueryDeviceByIdResponse.Data")
	proto.RegisterType((*Device)(nil), "driverdevice.Device")
	proto.RegisterMapType((map[string]string)(nil), "driverdevice.Device.ExternalEntry")
	proto.RegisterType((*QueryDeviceListRequest)(nil), "driverdevice.QueryDeviceListRequest")
	proto.RegisterType((*QueryDeviceListResponse)(nil), "driverdevice.QueryDeviceListResponse")
	proto.RegisterType((*QueryDeviceListResponse_Data)(nil), "driverdevice.QueryDeviceListResponse.Data")
	proto.RegisterType((*AddDevice)(nil), "driverdevice.AddDevice")
	proto.RegisterMapType((map[string]string)(nil), "driverdevice.AddDevice.ExternalEntry")
	proto.RegisterType((*UpdateDevice)(nil), "driverdevice.UpdateDevice")
	proto.RegisterMapType((map[string]string)(nil), "driverdevice.UpdateDevice.ExternalEntry")
	proto.RegisterType((*CreateDeviceRequest)(nil), "driverdevice.CreateDeviceRequest")
	proto.RegisterType((*CreateDeviceRequestResponse)(nil), "driverdevice.CreateDeviceRequestResponse")
	proto.RegisterType((*CreateDeviceRequestResponse_Data)(nil), "driverdevice.CreateDeviceRequestResponse.Data")
	proto.RegisterType((*UpdateDeviceRequestResponse)(nil), "driverdevice.UpdateDeviceRequestResponse")
	proto.RegisterType((*UpdateDeviceRequestResponse_Data)(nil), "driverdevice.UpdateDeviceRequestResponse.Data")
	proto.RegisterType((*UpdateDeviceRequest)(nil), "driverdevice.UpdateDeviceRequest")
	proto.RegisterType((*CreateDeviceAndConnectRequest)(nil), "driverdevice.CreateDeviceAndConnectRequest")
	proto.RegisterType((*CreateDeviceAndConnectRequestResponse)(nil), "driverdevice.CreateDeviceAndConnectRequestResponse")
	proto.RegisterType((*CreateDeviceAndConnectRequestResponse_Data)(nil), "driverdevice.CreateDeviceAndConnectRequestResponse.Data")
	proto.RegisterType((*DeleteDeviceRequest)(nil), "driverdevice.DeleteDeviceRequest")
	proto.RegisterType((*DeleteDeviceResponse)(nil), "driverdevice.DeleteDeviceResponse")
	proto.RegisterType((*GetDeviceConnectStatusRequest)(nil), "driverdevice.GetDeviceConnectStatusRequest")
	proto.RegisterType((*GetDeviceConnectStatusResponse)(nil), "driverdevice.GetDeviceConnectStatusResponse")
	proto.RegisterType((*GetDeviceConnectStatusResponse_Data)(nil), "driverdevice.GetDeviceConnectStatusResponse.Data")
}

func init() { proto.RegisterFile("driverdevice/device.proto", fileDescriptor_d977e3d1d866a4e5) }

var fileDescriptor_d977e3d1d866a4e5 = []byte{
	// 1261 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x58, 0x6f, 0x6f, 0xdb, 0x44,
	0x18, 0x8f, 0xd3, 0x34, 0x4d, 0x9e, 0xa4, 0x6d, 0xb8, 0x96, 0xce, 0x75, 0x5b, 0xd4, 0x59, 0x54,
	0x84, 0x6e, 0x4d, 0x20, 0x05, 0x34, 0x31, 0x69, 0xa2, 0x69, 0x3a, 0x14, 0x51, 0xb6, 0xe1, 0x51,
	0x81, 0x10, 0x62, 0xb8, 0xbe, 0x6b, 0xb1, 0xe6, 0x9c, 0x8d, 0x7d, 0xe9, 0x88, 0x90, 0xe0, 0xfd,
	0x24, 0xbe, 0x03, 0x9f, 0x84, 0xef, 0xc0, 0x6b, 0x24, 0x78, 0x83, 0x90, 0x78, 0xc5, 0x57, 0x40,
	0xbe, 0x73, 0x32, 0x5f, 0xe2, 0x38, 0x29, 0x0d, 0x63, 0x2f, 0x78, 0x15, 0x3f, 0x77, 0xcf, 0x3d,
	0x7f, 0x7e, 0xf7, 0xfc, 0x9e, 0xdc, 0x1d, 0xac, 0x63, 0xdf, 0xbe, 0x20, 0x3e, 0x26, 0x17, 0xb6,
	0x45, 0xea, 0xe2, 0xa7, 0xe6, 0xf9, 0x2e, 0x73, 0x51, 0x39, 0x3e, 0xa5, 0x45, 0x8a, 0x96, 0xdb,
	0xe9, 0xb8, 0xb4, 0x2e, 0x7e, 0x84, 0xa2, 0xfe, 0x2d, 0xac, 0x1f, 0xba, 0x94, 0x12, 0x8b, 0xb5,
	0x5d, 0xf6, 0xc0, 0x31, 0xd9, 0x99, 0xeb, 0x77, 0x0c, 0xf2, 0x75, 0x97, 0x04, 0x0c, 0x35, 0xa1,
	0x74, 0x6a, 0x06, 0x24, 0x12, 0x55, 0x65, 0x5b, 0xa9, 0x96, 0x1a, 0xdb, 0xb5, 0xb8, 0xb5, 0x5a,
	0xf3, 0x99, 0xc2, 0x87, 0x24, 0x08, 0xcc, 0x73, 0x62, 0xc4, 0x17, 0x21, 0x0d, 0x0a, 0x22, 0x8a,
	0x36, 0x56, 0xb3, 0xdb, 0x4a, 0xb5, 0x68, 0x0c, 0x64, 0xfd, 0x57, 0x05, 0xb4, 0x24, 0xef, 0x81,
	0xe7, 0xd2, 0x80, 0xa0, 0xf7, 0xa0, 0x2c, 0x2c, 0x09, 0x39, 0xf2, 0xbf, 0x29, 0xfb, 0x3f, 0xe4,
	0x3f, 0x7d, 0x1d, 0x43, 0x5a, 0x81, 0x0e, 0x20, 0x87, 0x4d, 0x66, 0x72, 0xc7, 0xa5, 0xc6, 0x5e,
	0x2d, 0x8e, 0x4a, 0x6d, 0xbc, 0xe7, 0x5a, 0xcb, 0x64, 0xa6, 0xc1, 0x97, 0x6a, 0xb7, 0x21, 0x17,
	0x4a, 0x68, 0x1f, 0xf2, 0x0f, 0x99, 0xc9, 0xba, 0x01, 0x0f, 0x63, 0xa9, 0xb1, 0x91, 0x68, 0x4c,
	0xa8, 0x18, 0x91, 0xaa, 0xfe, 0x1d, 0x6c, 0xb6, 0xec, 0xc0, 0xfa, 0xcf, 0x00, 0xfe, 0x5d, 0x81,
	0xad, 0x31, 0x01, 0xcc, 0x0c, 0xe3, 0x96, 0x84, 0xf1, 0x1b, 0x32, 0x2c, 0xa9, 0xce, 0x67, 0x06,
	0xb3, 0x03, 0x6b, 0x1f, 0x75, 0x89, 0xdf, 0x6b, 0x71, 0xa5, 0x66, 0xaf, 0x8d, 0x67, 0x09, 0xf0,
	0x12, 0x64, 0x07, 0xd0, 0x66, 0xdb, 0x58, 0xff, 0x59, 0x81, 0x6b, 0x23, 0xee, 0x66, 0x06, 0xe7,
	0x1d, 0x09, 0xce, 0x5d, 0x39, 0xfd, 0x31, 0x6e, 0xe3, 0x40, 0xbe, 0x15, 0x01, 0x79, 0x13, 0xf2,
	0x62, 0x51, 0x14, 0xc3, 0xea, 0xd0, 0xc6, 0xf0, 0x1f, 0x23, 0xd2, 0xd1, 0x7f, 0xcb, 0x41, 0x5e,
	0x0c, 0x85, 0xe9, 0xda, 0x98, 0x2f, 0x2a, 0x1a, 0x59, 0x1b, 0x23, 0x04, 0x39, 0x6a, 0x76, 0x48,
	0x04, 0x00, 0xff, 0x46, 0x5b, 0x00, 0x9e, 0xef, 0xe2, 0xae, 0xc5, 0x1e, 0xd9, 0x58, 0x9d, 0xe3,
	0x33, 0xc5, 0x68, 0xa4, 0x8d, 0xd1, 0x06, 0x14, 0x85, 0xdd, 0x47, 0x01, 0x55, 0x73, 0xf1, 0x9a,
	0x7c, 0x48, 0x51, 0x03, 0xf2, 0x81, 0xd8, 0xe1, 0x79, 0xbe, 0xc3, 0x5a, 0x52, 0x60, 0xfd, 0x0d,
	0x16, 0x9a, 0x68, 0x0d, 0xf2, 0x01, 0xb1, 0x7c, 0xc2, 0xd4, 0x3c, 0xb7, 0x16, 0x49, 0x3c, 0x56,
	0x4f, 0x5d, 0x88, 0x62, 0xf5, 0xc2, 0x58, 0x3d, 0xd7, 0x67, 0x6a, 0x41, 0xc4, 0x1a, 0x7e, 0xa3,
	0x0a, 0xcc, 0x39, 0x26, 0x53, 0x8b, 0x7c, 0x28, 0xfc, 0xe4, 0x23, 0x2e, 0x55, 0x21, 0x1a, 0x71,
	0x69, 0xc8, 0x21, 0xc7, 0xb5, 0x4c, 0x66, 0xbb, 0x54, 0x2d, 0x89, 0x78, 0xfb, 0x72, 0x98, 0x8c,
	0x67, 0xfa, 0x84, 0xf2, 0x54, 0xcb, 0x62, 0x52, 0x0c, 0xb4, 0x31, 0xd2, 0xa1, 0xdc, 0x31, 0x69,
	0xf7, 0xcc, 0xb4, 0x58, 0xd7, 0x27, 0xbe, 0xba, 0xc8, 0xe7, 0xa5, 0x31, 0xb4, 0x0a, 0xf3, 0x1d,
	0x17, 0x13, 0x47, 0x5d, 0xe2, 0x93, 0x42, 0x40, 0x77, 0xa0, 0x70, 0xf4, 0x0d, 0x23, 0x3e, 0x35,
	0x1d, 0x75, 0x79, 0x7b, 0xae, 0x5a, 0x6a, 0xe8, 0x49, 0x40, 0xd4, 0xfa, 0x4a, 0x47, 0x94, 0xf9,
	0x3d, 0x63, 0xb0, 0x06, 0x6d, 0x43, 0x09, 0x93, 0xc0, 0xf2, 0x6d, 0x8f, 0x47, 0x5d, 0xe1, 0xb6,
	0xe3, 0x43, 0x68, 0x13, 0x8a, 0xcc, 0x37, 0x69, 0xc0, 0x11, 0x79, 0x49, 0xec, 0xd1, 0x60, 0x00,
	0xad, 0x43, 0x21, 0x70, 0xcc, 0x0b, 0x12, 0x66, 0x85, 0xf8, 0xe4, 0x02, 0x97, 0xdb, 0x38, 0x44,
	0xdb, 0x23, 0xbe, 0xed, 0x62, 0x75, 0x45, 0xa0, 0x2d, 0x24, 0xed, 0x36, 0x2c, 0x4a, 0xd1, 0x84,
	0x40, 0x3e, 0x26, 0xbd, 0xa8, 0x56, 0xc2, 0xcf, 0x30, 0xd7, 0x0b, 0xd3, 0xe9, 0xf6, 0xab, 0x45,
	0x08, 0xef, 0x66, 0x6f, 0x29, 0xfa, 0xe7, 0x12, 0x47, 0x8f, 0xed, 0x80, 0xcd, 0x90, 0xa3, 0xfa,
	0x9f, 0x32, 0x27, 0x85, 0xf9, 0xe7, 0xce, 0xc9, 0xb8, 0xdb, 0x38, 0x27, 0x8f, 0x23, 0x4e, 0xae,
	0xc2, 0x3c, 0x73, 0x99, 0xe9, 0xf0, 0x10, 0x16, 0x0d, 0x21, 0xa0, 0x1a, 0x2c, 0x08, 0x53, 0x81,
	0x9a, 0xe5, 0x85, 0x90, 0x4c, 0xd5, 0xbe, 0x92, 0xfe, 0x34, 0x07, 0xc5, 0x03, 0x8c, 0x23, 0xba,
	0xf6, 0xe9, 0xa9, 0x8c, 0xa5, 0x67, 0x36, 0x95, 0x9e, 0x73, 0x63, 0xe9, 0x99, 0x9b, 0x9a, 0x9e,
	0x82, 0x86, 0xf3, 0x23, 0x34, 0xcc, 0x8f, 0xd2, 0x70, 0x61, 0x84, 0x86, 0x85, 0x64, 0x1a, 0x16,
	0xd3, 0x68, 0x08, 0x13, 0x68, 0x58, 0x4a, 0xa3, 0x61, 0x39, 0x4e, 0xc3, 0x83, 0x18, 0x0d, 0x17,
	0x39, 0xfa, 0x3b, 0x72, 0xc2, 0x03, 0xa4, 0xa7, 0x65, 0xe2, 0xd2, 0x04, 0x26, 0x2e, 0x0f, 0x31,
	0xf1, 0x6a, 0xb4, 0xfa, 0x31, 0x07, 0xe5, 0x13, 0x0f, 0x9b, 0x8c, 0x48, 0xed, 0xbb, 0x32, 0xd2,
	0xbe, 0xff, 0xaf, 0x8f, 0x7f, 0x54, 0x1f, 0xad, 0x91, 0xfa, 0xa8, 0xca, 0x09, 0xc7, 0xc1, 0x7f,
	0x31, 0x4b, 0xe4, 0xa9, 0x02, 0x2b, 0x87, 0x3e, 0x19, 0x44, 0x39, 0xcb, 0xb3, 0x51, 0x7d, 0x70,
	0xca, 0x10, 0xbd, 0xf1, 0xda, 0x18, 0xf2, 0x0c, 0x0e, 0x1a, 0xbf, 0x28, 0xb0, 0x91, 0x10, 0xcc,
	0xa0, 0xd5, 0x36, 0xa5, 0x56, 0x5b, 0x1b, 0x3a, 0xfd, 0x8d, 0x5f, 0x18, 0x6b, 0xb7, 0x57, 0x6f,
	0xf8, 0xda, 0x3b, 0x51, 0xc3, 0x96, 0x5a, 0xb3, 0x32, 0xb9, 0x35, 0x87, 0xd9, 0xc5, 0x0b, 0xe2,
	0x52, 0xd9, 0xa5, 0x2c, 0x7c, 0x31, 0xb2, 0xfb, 0x41, 0x81, 0x95, 0x84, 0x20, 0x67, 0x52, 0x48,
	0x8d, 0xa1, 0x42, 0xd2, 0x52, 0xb0, 0xe9, 0xd7, 0xd2, 0x03, 0xd8, 0x8a, 0x57, 0xc4, 0x01, 0xc5,
	0xd1, 0xf5, 0x60, 0xb4, 0x3a, 0x95, 0xe9, 0xaa, 0xf3, 0x2f, 0x05, 0x76, 0x52, 0x4d, 0xce, 0xf0,
	0x50, 0x71, 0x2c, 0xd5, 0xc2, 0xad, 0xf1, 0x95, 0x3e, 0x36, 0x88, 0xf8, 0x11, 0x23, 0x61, 0x4f,
	0x95, 0x69, 0xf6, 0xb4, 0x0b, 0x2b, 0x2d, 0xe2, 0x90, 0x7f, 0x63, 0x4b, 0xd3, 0x2e, 0xa6, 0x9f,
	0xc2, 0xaa, 0xec, 0x76, 0x56, 0xb0, 0xea, 0xdf, 0xc3, 0xd6, 0xfb, 0x84, 0x09, 0xb3, 0xf2, 0x6d,
	0xf1, 0x39, 0xa5, 0xf6, 0x87, 0x02, 0xaf, 0x8c, 0x8b, 0x20, 0xca, 0xf2, 0x48, 0xda, 0xfa, 0x37,
	0xe5, 0x1d, 0x4a, 0x5f, 0x3b, 0xdb, 0x4e, 0x70, 0x95, 0x5b, 0xf7, 0xee, 0xc7, 0x50, 0x8e, 0xff,
	0xdb, 0xa3, 0x0a, 0x94, 0x4f, 0xe8, 0x07, 0xd4, 0x7d, 0x22, 0xe4, 0x4a, 0x06, 0x01, 0xe4, 0xef,
	0xd3, 0x63, 0x9b, 0x92, 0x8a, 0x82, 0x4a, 0xb0, 0x70, 0xff, 0xec, 0x8c, 0x0b, 0x59, 0x54, 0x86,
	0xc2, 0x09, 0x3d, 0xb0, 0x98, 0x7d, 0x41, 0x2a, 0x73, 0xe1, 0x54, 0xcb, 0x0e, 0xcc, 0x53, 0x87,
	0x54, 0x72, 0xbb, 0x55, 0x58, 0x94, 0xdc, 0x71, 0x23, 0xf7, 0x8e, 0xdb, 0xf7, 0x8e, 0x2a, 0x19,
	0x6e, 0xe4, 0xee, 0x5d, 0x2e, 0x28, 0x8d, 0x9f, 0xf2, 0x50, 0x34, 0x3c, 0x2b, 0x3a, 0xf7, 0xd8,
	0x80, 0x46, 0x1f, 0x74, 0xd0, 0x6b, 0x93, 0x9f, 0x7c, 0xf8, 0x8e, 0x6a, 0xd5, 0x69, 0xdf, 0x86,
	0xf4, 0x0c, 0xf2, 0xe1, 0xe5, 0xc4, 0x77, 0x0d, 0xb4, 0x3b, 0xd5, 0xe3, 0x87, 0x70, 0x78, 0xe3,
	0x12, 0x0f, 0x25, 0x7a, 0x06, 0x75, 0x61, 0x2d, 0xb9, 0x30, 0xd0, 0x8d, 0xe9, 0xca, 0x47, 0x78,
	0xbd, 0x79, 0x99, 0x5a, 0xd3, 0x33, 0xe8, 0x4b, 0x58, 0x1e, 0xba, 0xdf, 0xa0, 0x57, 0x27, 0x5c,
	0x7f, 0x84, 0xa3, 0x9d, 0xa9, 0x2e, 0x49, 0x23, 0x1e, 0x9a, 0xbd, 0x36, 0x4e, 0xf1, 0x10, 0x7b,
	0xda, 0x49, 0xf1, 0x10, 0x7f, 0x1a, 0xd1, 0x33, 0xe8, 0x0b, 0x28, 0xc7, 0xdb, 0x29, 0xba, 0x3e,
	0xf1, 0x50, 0xa1, 0xbd, 0x3e, 0xf5, 0xb9, 0x43, 0xd8, 0x97, 0x4e, 0xe0, 0xd7, 0x27, 0xfe, 0xad,
	0x0f, 0xdb, 0x4f, 0xf9, 0xe7, 0xd7, 0x33, 0xe8, 0x93, 0x90, 0x67, 0xcf, 0x7a, 0xe5, 0xb0, 0xfd,
	0x84, 0xf6, 0xad, 0xe9, 0x69, 0x2a, 0x7d, 0xc3, 0xcd, 0xb7, 0x3f, 0xdb, 0x3f, 0xb7, 0xd9, 0x57,
	0xdd, 0xd3, 0x9a, 0xe5, 0x76, 0xea, 0x4f, 0x6c, 0x6a, 0xed, 0x39, 0x36, 0x7d, 0x5c, 0x27, 0xf8,
	0x9c, 0xec, 0x09, 0x03, 0x7b, 0xfc, 0x95, 0xb8, 0x1e, 0xb7, 0x76, 0x9a, 0xe7, 0x63, 0xfb, 0x7f,
	0x07, 0x00, 0x00, 0xff, 0xff, 0x35, 0xe8, 0xf7, 0x7a, 0x7f, 0x16, 0x00, 0x00,
}
