// Code generated by protoc-gen-go. DO NOT EDIT.
// source: driverproduct/product.proto

package driverproduct

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	drivercommon "github.com/winc-link/edge-driver-proto/drivercommon"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ProductNodeType int32

const (
	ProductNodeType_UnKnow    ProductNodeType = 0
	ProductNodeType_Gateway   ProductNodeType = 1
	ProductNodeType_Device    ProductNodeType = 2
	ProductNodeType_SubDevice ProductNodeType = 3
)

var ProductNodeType_name = map[int32]string{
	0: "UnKnow",
	1: "Gateway",
	2: "Device",
	3: "SubDevice",
}

var ProductNodeType_value = map[string]int32{
	"UnKnow":    0,
	"Gateway":   1,
	"Device":    2,
	"SubDevice": 3,
}

func (x ProductNodeType) String() string {
	return proto.EnumName(ProductNodeType_name, int32(x))
}

func (ProductNodeType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b1add4cf04e428fc, []int{0}
}

type ProductNetType int32

const (
	ProductNetType_Other    ProductNetType = 0
	ProductNetType_Cellular ProductNetType = 1
	ProductNetType_Wifi     ProductNetType = 2
	ProductNetType_Ethernet ProductNetType = 3
	ProductNetType_NB       ProductNetType = 4
)

var ProductNetType_name = map[int32]string{
	0: "Other",
	1: "Cellular",
	2: "Wifi",
	3: "Ethernet",
	4: "NB",
}

var ProductNetType_value = map[string]int32{
	"Other":    0,
	"Cellular": 1,
	"Wifi":     2,
	"Ethernet": 3,
	"NB":       4,
}

func (x ProductNetType) String() string {
	return proto.EnumName(ProductNetType_name, int32(x))
}

func (ProductNetType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b1add4cf04e428fc, []int{1}
}

type ProtocolType int32

const (
	ProtocolType_MQTT               ProtocolType = 0
	ProtocolType_TCP                ProtocolType = 1
	ProtocolType_UDP                ProtocolType = 2
	ProtocolType_CoAP               ProtocolType = 3
	ProtocolType_HTTP               ProtocolType = 4
	ProtocolType_WebSocket          ProtocolType = 5
	ProtocolType_ModbusTCP          ProtocolType = 6
	ProtocolType_GB28181            ProtocolType = 7
	ProtocolType_SiemensS7          ProtocolType = 8
	ProtocolType_IEC104             ProtocolType = 9
	ProtocolType_UnknowProtocolType ProtocolType = 99
)

var ProtocolType_name = map[int32]string{
	0:  "MQTT",
	1:  "TCP",
	2:  "UDP",
	3:  "CoAP",
	4:  "HTTP",
	5:  "WebSocket",
	6:  "ModbusTCP",
	7:  "GB28181",
	8:  "SiemensS7",
	9:  "IEC104",
	99: "UnknowProtocolType",
}

var ProtocolType_value = map[string]int32{
	"MQTT":               0,
	"TCP":                1,
	"UDP":                2,
	"CoAP":               3,
	"HTTP":               4,
	"WebSocket":          5,
	"ModbusTCP":          6,
	"GB28181":            7,
	"SiemensS7":          8,
	"IEC104":             9,
	"UnknowProtocolType": 99,
}

func (x ProtocolType) String() string {
	return proto.EnumName(ProtocolType_name, int32(x))
}

func (ProtocolType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b1add4cf04e428fc, []int{2}
}

type DataType int32

const (
	DataType_INT    DataType = 0
	DataType_FLOAT  DataType = 1
	DataType_TEXT   DataType = 2
	DataType_DATE   DataType = 3
	DataType_BOOL   DataType = 4
	DataType_ENUM   DataType = 5
	DataType_STRUCT DataType = 6
	DataType_ARRAY  DataType = 7
)

var DataType_name = map[int32]string{
	0: "INT",
	1: "FLOAT",
	2: "TEXT",
	3: "DATE",
	4: "BOOL",
	5: "ENUM",
	6: "STRUCT",
	7: "ARRAY",
}

var DataType_value = map[string]int32{
	"INT":    0,
	"FLOAT":  1,
	"TEXT":   2,
	"DATE":   3,
	"BOOL":   4,
	"ENUM":   5,
	"STRUCT": 6,
	"ARRAY":  7,
}

func (x DataType) String() string {
	return proto.EnumName(DataType_name, int32(x))
}

func (DataType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b1add4cf04e428fc, []int{3}
}

type QueryProductListRequest struct {
	BaseRequest          *drivercommon.BaseRequestMessage `protobuf:"bytes,1,opt,name=baseRequest,proto3" json:"baseRequest,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *QueryProductListRequest) Reset()         { *m = QueryProductListRequest{} }
func (m *QueryProductListRequest) String() string { return proto.CompactTextString(m) }
func (*QueryProductListRequest) ProtoMessage()    {}
func (*QueryProductListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1add4cf04e428fc, []int{0}
}

func (m *QueryProductListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryProductListRequest.Unmarshal(m, b)
}
func (m *QueryProductListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryProductListRequest.Marshal(b, m, deterministic)
}
func (m *QueryProductListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryProductListRequest.Merge(m, src)
}
func (m *QueryProductListRequest) XXX_Size() int {
	return xxx_messageInfo_QueryProductListRequest.Size(m)
}
func (m *QueryProductListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryProductListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryProductListRequest proto.InternalMessageInfo

func (m *QueryProductListRequest) GetBaseRequest() *drivercommon.BaseRequestMessage {
	if m != nil {
		return m.BaseRequest
	}
	return nil
}

type QueryProductListResponse struct {
	BaseResponse         *drivercommon.CommonResponse   `protobuf:"bytes,1,opt,name=baseResponse,proto3" json:"baseResponse,omitempty"`
	Data                 *QueryProductListResponse_Data `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *QueryProductListResponse) Reset()         { *m = QueryProductListResponse{} }
func (m *QueryProductListResponse) String() string { return proto.CompactTextString(m) }
func (*QueryProductListResponse) ProtoMessage()    {}
func (*QueryProductListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1add4cf04e428fc, []int{1}
}

func (m *QueryProductListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryProductListResponse.Unmarshal(m, b)
}
func (m *QueryProductListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryProductListResponse.Marshal(b, m, deterministic)
}
func (m *QueryProductListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryProductListResponse.Merge(m, src)
}
func (m *QueryProductListResponse) XXX_Size() int {
	return xxx_messageInfo_QueryProductListResponse.Size(m)
}
func (m *QueryProductListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryProductListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryProductListResponse proto.InternalMessageInfo

func (m *QueryProductListResponse) GetBaseResponse() *drivercommon.CommonResponse {
	if m != nil {
		return m.BaseResponse
	}
	return nil
}

func (m *QueryProductListResponse) GetData() *QueryProductListResponse_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type QueryProductListResponse_Data struct {
	Total                uint32     `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Products             []*Product `protobuf:"bytes,2,rep,name=products,proto3" json:"products,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *QueryProductListResponse_Data) Reset()         { *m = QueryProductListResponse_Data{} }
func (m *QueryProductListResponse_Data) String() string { return proto.CompactTextString(m) }
func (*QueryProductListResponse_Data) ProtoMessage()    {}
func (*QueryProductListResponse_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1add4cf04e428fc, []int{1, 0}
}

func (m *QueryProductListResponse_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryProductListResponse_Data.Unmarshal(m, b)
}
func (m *QueryProductListResponse_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryProductListResponse_Data.Marshal(b, m, deterministic)
}
func (m *QueryProductListResponse_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryProductListResponse_Data.Merge(m, src)
}
func (m *QueryProductListResponse_Data) XXX_Size() int {
	return xxx_messageInfo_QueryProductListResponse_Data.Size(m)
}
func (m *QueryProductListResponse_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryProductListResponse_Data.DiscardUnknown(m)
}

var xxx_messageInfo_QueryProductListResponse_Data proto.InternalMessageInfo

func (m *QueryProductListResponse_Data) GetTotal() uint32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *QueryProductListResponse_Data) GetProducts() []*Product {
	if m != nil {
		return m.Products
	}
	return nil
}

type QueryProductByIdRequest struct {
	BaseRequest          *drivercommon.BaseRequestMessage `protobuf:"bytes,1,opt,name=baseRequest,proto3" json:"baseRequest,omitempty"`
	Id                   string                           `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *QueryProductByIdRequest) Reset()         { *m = QueryProductByIdRequest{} }
func (m *QueryProductByIdRequest) String() string { return proto.CompactTextString(m) }
func (*QueryProductByIdRequest) ProtoMessage()    {}
func (*QueryProductByIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1add4cf04e428fc, []int{2}
}

func (m *QueryProductByIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryProductByIdRequest.Unmarshal(m, b)
}
func (m *QueryProductByIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryProductByIdRequest.Marshal(b, m, deterministic)
}
func (m *QueryProductByIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryProductByIdRequest.Merge(m, src)
}
func (m *QueryProductByIdRequest) XXX_Size() int {
	return xxx_messageInfo_QueryProductByIdRequest.Size(m)
}
func (m *QueryProductByIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryProductByIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryProductByIdRequest proto.InternalMessageInfo

func (m *QueryProductByIdRequest) GetBaseRequest() *drivercommon.BaseRequestMessage {
	if m != nil {
		return m.BaseRequest
	}
	return nil
}

func (m *QueryProductByIdRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Product struct {
	CreateAt             uint64                   `protobuf:"varint,1,opt,name=createAt,proto3" json:"createAt,omitempty"`
	Id                   string                   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string                   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description          string                   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	NodeType             ProductNodeType          `protobuf:"varint,5,opt,name=NodeType,proto3,enum=driverproduct.ProductNodeType" json:"NodeType,omitempty"`
	DataFormat           string                   `protobuf:"bytes,6,opt,name=dataFormat,proto3" json:"dataFormat,omitempty"`
	Platform             drivercommon.IotPlatform `protobuf:"varint,7,opt,name=Platform,proto3,enum=drivercommon.IotPlatform" json:"Platform,omitempty"`
	NetType              ProductNetType           `protobuf:"varint,8,opt,name=netType,proto3,enum=driverproduct.ProductNetType" json:"netType,omitempty"`
	Protocol             ProtocolType             `protobuf:"varint,13,opt,name=protocol,proto3,enum=driverproduct.ProtocolType" json:"protocol,omitempty"`
	Properties           []*Properties            `protobuf:"bytes,9,rep,name=properties,proto3" json:"properties,omitempty"`
	Events               []*Events                `protobuf:"bytes,10,rep,name=events,proto3" json:"events,omitempty"`
	Actions              []*Actions               `protobuf:"bytes,11,rep,name=actions,proto3" json:"actions,omitempty"`
	Key                  string                   `protobuf:"bytes,12,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1add4cf04e428fc, []int{3}
}

func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (m *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(m, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetCreateAt() uint64 {
	if m != nil {
		return m.CreateAt
	}
	return 0
}

func (m *Product) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Product) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Product) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Product) GetNodeType() ProductNodeType {
	if m != nil {
		return m.NodeType
	}
	return ProductNodeType_UnKnow
}

func (m *Product) GetDataFormat() string {
	if m != nil {
		return m.DataFormat
	}
	return ""
}

func (m *Product) GetPlatform() drivercommon.IotPlatform {
	if m != nil {
		return m.Platform
	}
	return drivercommon.IotPlatform_LocalIot
}

func (m *Product) GetNetType() ProductNetType {
	if m != nil {
		return m.NetType
	}
	return ProductNetType_Other
}

func (m *Product) GetProtocol() ProtocolType {
	if m != nil {
		return m.Protocol
	}
	return ProtocolType_MQTT
}

func (m *Product) GetProperties() []*Properties {
	if m != nil {
		return m.Properties
	}
	return nil
}

func (m *Product) GetEvents() []*Events {
	if m != nil {
		return m.Events
	}
	return nil
}

func (m *Product) GetActions() []*Actions {
	if m != nil {
		return m.Actions
	}
	return nil
}

func (m *Product) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type Properties struct {
	ModelName   string    `protobuf:"bytes,1,opt,name=modelName,proto3" json:"modelName,omitempty"`
	ProductId   string    `protobuf:"bytes,2,opt,name=productId,proto3" json:"productId,omitempty"`
	Name        string    `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Code        string    `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`
	Description string    `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Required    bool      `protobuf:"varint,9,opt,name=required,proto3" json:"required,omitempty"`
	AccessMode  string    `protobuf:"bytes,6,opt,name=accessMode,proto3" json:"accessMode,omitempty"`
	TypeSpec    *TypeSpec `protobuf:"bytes,7,opt,name=typeSpec,proto3" json:"typeSpec,omitempty"`
	Extend      string    `protobuf:"bytes,8,opt,name=extend,proto3" json:"extend,omitempty"`
	// string readFormula = 10;
	// string writeFormula = 11;
	// string registerAddr = 12;
	// string registerType = 13;
	External             map[string]string `protobuf:"bytes,14,rep,name=External,proto3" json:"External,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Properties) Reset()         { *m = Properties{} }
func (m *Properties) String() string { return proto.CompactTextString(m) }
func (*Properties) ProtoMessage()    {}
func (*Properties) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1add4cf04e428fc, []int{4}
}

func (m *Properties) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Properties.Unmarshal(m, b)
}
func (m *Properties) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Properties.Marshal(b, m, deterministic)
}
func (m *Properties) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Properties.Merge(m, src)
}
func (m *Properties) XXX_Size() int {
	return xxx_messageInfo_Properties.Size(m)
}
func (m *Properties) XXX_DiscardUnknown() {
	xxx_messageInfo_Properties.DiscardUnknown(m)
}

var xxx_messageInfo_Properties proto.InternalMessageInfo

func (m *Properties) GetModelName() string {
	if m != nil {
		return m.ModelName
	}
	return ""
}

func (m *Properties) GetProductId() string {
	if m != nil {
		return m.ProductId
	}
	return ""
}

func (m *Properties) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Properties) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Properties) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Properties) GetRequired() bool {
	if m != nil {
		return m.Required
	}
	return false
}

func (m *Properties) GetAccessMode() string {
	if m != nil {
		return m.AccessMode
	}
	return ""
}

func (m *Properties) GetTypeSpec() *TypeSpec {
	if m != nil {
		return m.TypeSpec
	}
	return nil
}

func (m *Properties) GetExtend() string {
	if m != nil {
		return m.Extend
	}
	return ""
}

func (m *Properties) GetExternal() map[string]string {
	if m != nil {
		return m.External
	}
	return nil
}

type Events struct {
	ModelName            string          `protobuf:"bytes,1,opt,name=ModelName,proto3" json:"ModelName,omitempty"`
	ProductId            string          `protobuf:"bytes,2,opt,name=productId,proto3" json:"productId,omitempty"`
	Name                 string          `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Code                 string          `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`
	Required             bool            `protobuf:"varint,8,opt,name=required,proto3" json:"required,omitempty"`
	Type                 string          `protobuf:"bytes,9,opt,name=type,proto3" json:"type,omitempty"`
	Description          string          `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	OutputParams         []*OutputParams `protobuf:"bytes,6,rep,name=OutputParams,proto3" json:"OutputParams,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Events) Reset()         { *m = Events{} }
func (m *Events) String() string { return proto.CompactTextString(m) }
func (*Events) ProtoMessage()    {}
func (*Events) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1add4cf04e428fc, []int{5}
}

func (m *Events) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Events.Unmarshal(m, b)
}
func (m *Events) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Events.Marshal(b, m, deterministic)
}
func (m *Events) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Events.Merge(m, src)
}
func (m *Events) XXX_Size() int {
	return xxx_messageInfo_Events.Size(m)
}
func (m *Events) XXX_DiscardUnknown() {
	xxx_messageInfo_Events.DiscardUnknown(m)
}

var xxx_messageInfo_Events proto.InternalMessageInfo

func (m *Events) GetModelName() string {
	if m != nil {
		return m.ModelName
	}
	return ""
}

func (m *Events) GetProductId() string {
	if m != nil {
		return m.ProductId
	}
	return ""
}

func (m *Events) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Events) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Events) GetRequired() bool {
	if m != nil {
		return m.Required
	}
	return false
}

func (m *Events) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Events) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Events) GetOutputParams() []*OutputParams {
	if m != nil {
		return m.OutputParams
	}
	return nil
}

type InputParams struct {
	Code                 string    `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name                 string    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	TypeSpec             *TypeSpec `protobuf:"bytes,3,opt,name=typeSpec,proto3" json:"typeSpec,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *InputParams) Reset()         { *m = InputParams{} }
func (m *InputParams) String() string { return proto.CompactTextString(m) }
func (*InputParams) ProtoMessage()    {}
func (*InputParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1add4cf04e428fc, []int{6}
}

func (m *InputParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InputParams.Unmarshal(m, b)
}
func (m *InputParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InputParams.Marshal(b, m, deterministic)
}
func (m *InputParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InputParams.Merge(m, src)
}
func (m *InputParams) XXX_Size() int {
	return xxx_messageInfo_InputParams.Size(m)
}
func (m *InputParams) XXX_DiscardUnknown() {
	xxx_messageInfo_InputParams.DiscardUnknown(m)
}

var xxx_messageInfo_InputParams proto.InternalMessageInfo

func (m *InputParams) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *InputParams) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *InputParams) GetTypeSpec() *TypeSpec {
	if m != nil {
		return m.TypeSpec
	}
	return nil
}

type OutputParams struct {
	Code                 string    `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name                 string    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	TypeSpec             *TypeSpec `protobuf:"bytes,3,opt,name=typeSpec,proto3" json:"typeSpec,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *OutputParams) Reset()         { *m = OutputParams{} }
func (m *OutputParams) String() string { return proto.CompactTextString(m) }
func (*OutputParams) ProtoMessage()    {}
func (*OutputParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1add4cf04e428fc, []int{7}
}

func (m *OutputParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OutputParams.Unmarshal(m, b)
}
func (m *OutputParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OutputParams.Marshal(b, m, deterministic)
}
func (m *OutputParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OutputParams.Merge(m, src)
}
func (m *OutputParams) XXX_Size() int {
	return xxx_messageInfo_OutputParams.Size(m)
}
func (m *OutputParams) XXX_DiscardUnknown() {
	xxx_messageInfo_OutputParams.DiscardUnknown(m)
}

var xxx_messageInfo_OutputParams proto.InternalMessageInfo

func (m *OutputParams) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *OutputParams) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *OutputParams) GetTypeSpec() *TypeSpec {
	if m != nil {
		return m.TypeSpec
	}
	return nil
}

type TypeSpec struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Specs                string   `protobuf:"bytes,2,opt,name=specs,proto3" json:"specs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TypeSpec) Reset()         { *m = TypeSpec{} }
func (m *TypeSpec) String() string { return proto.CompactTextString(m) }
func (*TypeSpec) ProtoMessage()    {}
func (*TypeSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1add4cf04e428fc, []int{8}
}

func (m *TypeSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TypeSpec.Unmarshal(m, b)
}
func (m *TypeSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TypeSpec.Marshal(b, m, deterministic)
}
func (m *TypeSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TypeSpec.Merge(m, src)
}
func (m *TypeSpec) XXX_Size() int {
	return xxx_messageInfo_TypeSpec.Size(m)
}
func (m *TypeSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_TypeSpec.DiscardUnknown(m)
}

var xxx_messageInfo_TypeSpec proto.InternalMessageInfo

func (m *TypeSpec) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *TypeSpec) GetSpecs() string {
	if m != nil {
		return m.Specs
	}
	return ""
}

type Actions struct {
	ModelName            string          `protobuf:"bytes,1,opt,name=ModelName,proto3" json:"ModelName,omitempty"`
	ProductId            string          `protobuf:"bytes,2,opt,name=productId,proto3" json:"productId,omitempty"`
	Name                 string          `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Code                 string          `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`
	Required             bool            `protobuf:"varint,9,opt,name=required,proto3" json:"required,omitempty"`
	CallType             string          `protobuf:"bytes,10,opt,name=callType,proto3" json:"callType,omitempty"`
	Description          string          `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	InputParams          []*InputParams  `protobuf:"bytes,6,rep,name=InputParams,proto3" json:"InputParams,omitempty"`
	OutputParams         []*OutputParams `protobuf:"bytes,7,rep,name=OutputParams,proto3" json:"OutputParams,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Actions) Reset()         { *m = Actions{} }
func (m *Actions) String() string { return proto.CompactTextString(m) }
func (*Actions) ProtoMessage()    {}
func (*Actions) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1add4cf04e428fc, []int{9}
}

func (m *Actions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Actions.Unmarshal(m, b)
}
func (m *Actions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Actions.Marshal(b, m, deterministic)
}
func (m *Actions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Actions.Merge(m, src)
}
func (m *Actions) XXX_Size() int {
	return xxx_messageInfo_Actions.Size(m)
}
func (m *Actions) XXX_DiscardUnknown() {
	xxx_messageInfo_Actions.DiscardUnknown(m)
}

var xxx_messageInfo_Actions proto.InternalMessageInfo

func (m *Actions) GetModelName() string {
	if m != nil {
		return m.ModelName
	}
	return ""
}

func (m *Actions) GetProductId() string {
	if m != nil {
		return m.ProductId
	}
	return ""
}

func (m *Actions) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Actions) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Actions) GetRequired() bool {
	if m != nil {
		return m.Required
	}
	return false
}

func (m *Actions) GetCallType() string {
	if m != nil {
		return m.CallType
	}
	return ""
}

func (m *Actions) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Actions) GetInputParams() []*InputParams {
	if m != nil {
		return m.InputParams
	}
	return nil
}

func (m *Actions) GetOutputParams() []*OutputParams {
	if m != nil {
		return m.OutputParams
	}
	return nil
}

type QueryProductByIdResponse struct {
	BaseResponse         *drivercommon.CommonResponse   `protobuf:"bytes,1,opt,name=baseResponse,proto3" json:"baseResponse,omitempty"`
	Data                 *QueryProductByIdResponse_Data `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *QueryProductByIdResponse) Reset()         { *m = QueryProductByIdResponse{} }
func (m *QueryProductByIdResponse) String() string { return proto.CompactTextString(m) }
func (*QueryProductByIdResponse) ProtoMessage()    {}
func (*QueryProductByIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1add4cf04e428fc, []int{10}
}

func (m *QueryProductByIdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryProductByIdResponse.Unmarshal(m, b)
}
func (m *QueryProductByIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryProductByIdResponse.Marshal(b, m, deterministic)
}
func (m *QueryProductByIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryProductByIdResponse.Merge(m, src)
}
func (m *QueryProductByIdResponse) XXX_Size() int {
	return xxx_messageInfo_QueryProductByIdResponse.Size(m)
}
func (m *QueryProductByIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryProductByIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryProductByIdResponse proto.InternalMessageInfo

func (m *QueryProductByIdResponse) GetBaseResponse() *drivercommon.CommonResponse {
	if m != nil {
		return m.BaseResponse
	}
	return nil
}

func (m *QueryProductByIdResponse) GetData() *QueryProductByIdResponse_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type QueryProductByIdResponse_Data struct {
	Product              *Product `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryProductByIdResponse_Data) Reset()         { *m = QueryProductByIdResponse_Data{} }
func (m *QueryProductByIdResponse_Data) String() string { return proto.CompactTextString(m) }
func (*QueryProductByIdResponse_Data) ProtoMessage()    {}
func (*QueryProductByIdResponse_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1add4cf04e428fc, []int{10, 0}
}

func (m *QueryProductByIdResponse_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryProductByIdResponse_Data.Unmarshal(m, b)
}
func (m *QueryProductByIdResponse_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryProductByIdResponse_Data.Marshal(b, m, deterministic)
}
func (m *QueryProductByIdResponse_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryProductByIdResponse_Data.Merge(m, src)
}
func (m *QueryProductByIdResponse_Data) XXX_Size() int {
	return xxx_messageInfo_QueryProductByIdResponse_Data.Size(m)
}
func (m *QueryProductByIdResponse_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryProductByIdResponse_Data.DiscardUnknown(m)
}

var xxx_messageInfo_QueryProductByIdResponse_Data proto.InternalMessageInfo

func (m *QueryProductByIdResponse_Data) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

func init() {
	proto.RegisterEnum("driverproduct.ProductNodeType", ProductNodeType_name, ProductNodeType_value)
	proto.RegisterEnum("driverproduct.ProductNetType", ProductNetType_name, ProductNetType_value)
	proto.RegisterEnum("driverproduct.ProtocolType", ProtocolType_name, ProtocolType_value)
	proto.RegisterEnum("driverproduct.DataType", DataType_name, DataType_value)
	proto.RegisterType((*QueryProductListRequest)(nil), "driverproduct.QueryProductListRequest")
	proto.RegisterType((*QueryProductListResponse)(nil), "driverproduct.QueryProductListResponse")
	proto.RegisterType((*QueryProductListResponse_Data)(nil), "driverproduct.QueryProductListResponse.Data")
	proto.RegisterType((*QueryProductByIdRequest)(nil), "driverproduct.QueryProductByIdRequest")
	proto.RegisterType((*Product)(nil), "driverproduct.Product")
	proto.RegisterType((*Properties)(nil), "driverproduct.Properties")
	proto.RegisterMapType((map[string]string)(nil), "driverproduct.Properties.ExternalEntry")
	proto.RegisterType((*Events)(nil), "driverproduct.Events")
	proto.RegisterType((*InputParams)(nil), "driverproduct.InputParams")
	proto.RegisterType((*OutputParams)(nil), "driverproduct.OutputParams")
	proto.RegisterType((*TypeSpec)(nil), "driverproduct.TypeSpec")
	proto.RegisterType((*Actions)(nil), "driverproduct.Actions")
	proto.RegisterType((*QueryProductByIdResponse)(nil), "driverproduct.QueryProductByIdResponse")
	proto.RegisterType((*QueryProductByIdResponse_Data)(nil), "driverproduct.QueryProductByIdResponse.Data")
}

func init() { proto.RegisterFile("driverproduct/product.proto", fileDescriptor_b1add4cf04e428fc) }

var fileDescriptor_b1add4cf04e428fc = []byte{
	// 1166 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x56, 0xdd, 0x72, 0xdb, 0x44,
	0x14, 0x8e, 0x6c, 0xd9, 0x92, 0x8f, 0x93, 0xb0, 0xb3, 0x53, 0x5a, 0xd5, 0x2d, 0x1d, 0x8f, 0x2f,
	0x68, 0x26, 0x43, 0x9c, 0xc6, 0x0d, 0x24, 0x14, 0x66, 0xa8, 0xed, 0xb8, 0xe0, 0x21, 0x4e, 0xdc,
	0x8d, 0x32, 0x05, 0x66, 0x7a, 0x21, 0x4b, 0xdb, 0x54, 0xc4, 0xd6, 0xaa, 0xd2, 0x3a, 0xa9, 0xdf,
	0x05, 0x78, 0x1c, 0x9e, 0x81, 0xe1, 0x29, 0x78, 0x03, 0x98, 0x5d, 0xfd, 0x44, 0x52, 0x92, 0x12,
	0x66, 0x0a, 0x5c, 0x79, 0xcf, 0xee, 0x77, 0x7e, 0xf6, 0x3b, 0x9f, 0xbc, 0x07, 0xee, 0x39, 0x81,
	0x7b, 0x46, 0x03, 0x3f, 0x60, 0xce, 0xdc, 0xe6, 0x9b, 0xf1, 0x6f, 0xdb, 0x0f, 0x18, 0x67, 0x78,
	0x25, 0x77, 0xd8, 0xb8, 0x1b, 0x99, 0x36, 0x9b, 0xcd, 0x98, 0xb7, 0x19, 0xfd, 0x44, 0xc8, 0xd6,
	0x4b, 0xb8, 0xf3, 0x7c, 0x4e, 0x83, 0xc5, 0x38, 0x82, 0xee, 0xbb, 0x21, 0x27, 0xf4, 0xcd, 0x9c,
	0x86, 0x1c, 0xf7, 0xa0, 0x3e, 0xb1, 0x42, 0x1a, 0x9b, 0x86, 0xd2, 0x54, 0xd6, 0xea, 0x9d, 0x66,
	0x3b, 0x1b, 0xab, 0xdd, 0xbb, 0x00, 0x8c, 0x68, 0x18, 0x5a, 0x27, 0x94, 0x64, 0x9d, 0x5a, 0x7f,
	0x28, 0x60, 0x5c, 0x8e, 0x1f, 0xfa, 0xcc, 0x0b, 0x29, 0x7e, 0x0a, 0xcb, 0x11, 0x36, 0xb2, 0xe3,
	0x0c, 0xf7, 0xf3, 0x19, 0xfa, 0xf2, 0x27, 0xc1, 0x90, 0x9c, 0x07, 0x7e, 0x0a, 0xaa, 0x63, 0x71,
	0xcb, 0x28, 0x49, 0xcf, 0x4f, 0xda, 0xb9, 0x6b, 0xb7, 0xaf, 0x4b, 0xdc, 0xde, 0xb3, 0xb8, 0x45,
	0xa4, 0x67, 0x63, 0x0c, 0xaa, 0xb0, 0xf0, 0x2d, 0xa8, 0x70, 0xc6, 0xad, 0xa9, 0x2c, 0x62, 0x85,
	0x44, 0x06, 0xee, 0x80, 0x1e, 0x07, 0x0b, 0x8d, 0x52, 0xb3, 0xbc, 0x56, 0xef, 0xdc, 0x2e, 0xe4,
	0x88, 0xc3, 0x93, 0x14, 0xd7, 0x9a, 0xe5, 0x19, 0xed, 0x2d, 0x86, 0xce, 0x7b, 0x64, 0x14, 0xaf,
	0x42, 0xc9, 0x75, 0xe4, 0x85, 0x6b, 0xa4, 0xe4, 0x3a, 0xad, 0x5f, 0x54, 0xd0, 0xe2, 0x54, 0xb8,
	0x01, 0xba, 0x1d, 0x50, 0x8b, 0xd3, 0x6e, 0x14, 0x5c, 0x25, 0xa9, 0x5d, 0xf4, 0xc3, 0x18, 0x54,
	0xcf, 0x9a, 0x51, 0xa3, 0x2c, 0x77, 0xe4, 0x1a, 0x37, 0xa1, 0xee, 0xd0, 0xd0, 0x0e, 0x5c, 0x9f,
	0xbb, 0xcc, 0x33, 0x54, 0x79, 0x94, 0xdd, 0xc2, 0x4f, 0x40, 0x3f, 0x60, 0x0e, 0x35, 0x17, 0x3e,
	0x35, 0x2a, 0x4d, 0x65, 0x6d, 0xb5, 0xf3, 0xe0, 0x6a, 0x42, 0x12, 0x14, 0x49, 0xf1, 0xf8, 0x01,
	0x80, 0xa0, 0xfc, 0x19, 0x0b, 0x66, 0x16, 0x37, 0xaa, 0x32, 0x78, 0x66, 0x07, 0x7f, 0x0a, 0xfa,
	0x78, 0x6a, 0xf1, 0x57, 0x2c, 0x98, 0x19, 0x9a, 0x8c, 0x7d, 0x37, 0x4f, 0xcd, 0x90, 0xf1, 0x04,
	0x40, 0x52, 0x28, 0xde, 0x01, 0xcd, 0xa3, 0x5c, 0x56, 0xa4, 0x4b, 0xaf, 0x8f, 0xae, 0xa9, 0x28,
	0x02, 0x91, 0x04, 0x8d, 0x77, 0x64, 0x73, 0x39, 0xb3, 0xd9, 0xd4, 0x58, 0x91, 0x9e, 0xf7, 0x0a,
	0x9e, 0xc9, 0x71, 0x74, 0x91, 0xc4, 0xc2, 0x9f, 0x03, 0xf8, 0x01, 0xf3, 0x69, 0xc0, 0x5d, 0x1a,
	0x1a, 0x35, 0xa9, 0x8b, 0xbb, 0x97, 0x93, 0xc6, 0x00, 0x92, 0x01, 0xe3, 0x0d, 0xa8, 0xd2, 0x33,
	0xea, 0xf1, 0xd0, 0x00, 0xe9, 0xf6, 0x61, 0xc1, 0x6d, 0x20, 0x0f, 0x49, 0x0c, 0xc2, 0x8f, 0x40,
	0xb3, 0x6c, 0x41, 0x7c, 0x68, 0xd4, 0xaf, 0x94, 0x5f, 0x37, 0x3a, 0x25, 0x09, 0x0c, 0x23, 0x28,
	0x9f, 0xd2, 0x85, 0xb1, 0x2c, 0xd9, 0x15, 0xcb, 0xd6, 0xcf, 0x65, 0x80, 0x8b, 0x6a, 0xf0, 0x7d,
	0xa8, 0xcd, 0x98, 0x43, 0xa7, 0x07, 0xa2, 0xf9, 0x8a, 0x84, 0x5d, 0x6c, 0x88, 0xd3, 0x38, 0xf4,
	0x30, 0x11, 0xcb, 0xc5, 0xc6, 0x95, 0x9a, 0xc1, 0xa0, 0xda, 0xcc, 0xa1, 0xb1, 0x58, 0xe4, 0xba,
	0xa8, 0xa3, 0xca, 0x65, 0x1d, 0x35, 0x40, 0x0f, 0xe8, 0x9b, 0xb9, 0x1b, 0x50, 0xc7, 0xa8, 0x35,
	0x95, 0x35, 0x9d, 0xa4, 0xb6, 0xd0, 0x89, 0x65, 0xdb, 0x34, 0x0c, 0x47, 0x22, 0x6e, 0xac, 0x93,
	0x8b, 0x1d, 0xfc, 0x18, 0x74, 0xbe, 0xf0, 0xe9, 0x91, 0x4f, 0x6d, 0xa9, 0x93, 0x7a, 0xe7, 0x4e,
	0x81, 0x15, 0x33, 0x3e, 0x26, 0x29, 0x10, 0xdf, 0x86, 0x2a, 0x7d, 0xcb, 0xa9, 0xe7, 0x48, 0x91,
	0xd4, 0x48, 0x6c, 0xe1, 0x3e, 0xe8, 0x83, 0xb7, 0x9c, 0x06, 0x9e, 0x35, 0x35, 0x56, 0x25, 0xc5,
	0x0f, 0xaf, 0xed, 0x64, 0x3b, 0x41, 0x0e, 0x3c, 0x1e, 0x2c, 0x48, 0xea, 0xd8, 0xf8, 0x02, 0x56,
	0x72, 0x47, 0x49, 0x17, 0x94, 0xb4, 0x0b, 0xe2, 0xff, 0xe5, 0xcc, 0x9a, 0xce, 0x69, 0x4c, 0x6a,
	0x64, 0x3c, 0x29, 0xed, 0x2a, 0xad, 0x3f, 0x15, 0xa8, 0x46, 0x6d, 0x17, 0xec, 0x8f, 0x8a, 0xbd,
	0x19, 0xbd, 0xe7, 0xde, 0x64, 0x99, 0xd7, 0x0b, 0xcc, 0x63, 0x50, 0x05, 0x61, 0xb2, 0x23, 0x35,
	0x22, 0xd7, 0x37, 0xe8, 0xe5, 0x57, 0xb0, 0x7c, 0x38, 0xe7, 0xfe, 0x9c, 0x8f, 0xad, 0xc0, 0x9a,
	0x85, 0x46, 0x55, 0xd2, 0x58, 0xfc, 0x96, 0xb2, 0x10, 0x92, 0x73, 0x68, 0xfd, 0x08, 0xf5, 0xa1,
	0x97, 0x9a, 0x69, 0xd5, 0x4a, 0xa6, 0xea, 0xe4, 0x76, 0xa5, 0xcc, 0xed, 0xb2, 0x3a, 0x28, 0xdf,
	0x50, 0x07, 0xad, 0xd3, 0x7c, 0xb1, 0xff, 0x6e, 0xb2, 0x6d, 0xd0, 0x93, 0xdd, 0x94, 0x5b, 0x25,
	0xc3, 0xed, 0x2d, 0xa8, 0x84, 0x3e, 0xb5, 0xc3, 0x44, 0x14, 0xd2, 0x68, 0xfd, 0x5a, 0x02, 0x2d,
	0xfe, 0xae, 0xff, 0x73, 0x45, 0x14, 0xbf, 0x45, 0xf1, 0xa2, 0x58, 0x53, 0xf9, 0x07, 0x68, 0x80,
	0xf4, 0x49, 0xed, 0x1b, 0x28, 0xe3, 0xcb, 0x5c, 0x63, 0x63, 0x61, 0x34, 0x0a, 0xbc, 0x65, 0x10,
	0x24, 0xa7, 0x83, 0xa2, 0xae, 0xb4, 0x7f, 0xaa, 0xab, 0xdf, 0x0a, 0xc3, 0x47, 0xf4, 0x14, 0xff,
	0x0f, 0xc3, 0x47, 0x36, 0x71, 0x76, 0xf8, 0xd8, 0x8d, 0x87, 0x8f, 0x47, 0xa0, 0xc5, 0x6e, 0x71,
	0x19, 0xd7, 0x4d, 0x19, 0x09, 0x6c, 0x7d, 0x00, 0x1f, 0x14, 0x1e, 0x5a, 0x0c, 0x50, 0x3d, 0xf6,
	0xbe, 0xf5, 0xd8, 0x39, 0x5a, 0xc2, 0x75, 0xd0, 0xbe, 0xb6, 0x38, 0x3d, 0xb7, 0x16, 0x48, 0x11,
	0x07, 0x7b, 0xf4, 0xcc, 0xb5, 0x29, 0x2a, 0xe1, 0x15, 0xa8, 0x1d, 0xcd, 0x27, 0xb1, 0x59, 0x5e,
	0x1f, 0xc2, 0x6a, 0xfe, 0x75, 0xc4, 0x35, 0xa8, 0x1c, 0xf2, 0xd7, 0x34, 0x40, 0x4b, 0x78, 0x19,
	0xf4, 0x3e, 0x9d, 0x4e, 0xe7, 0x53, 0x2b, 0x40, 0x0a, 0xd6, 0x41, 0x7d, 0xe1, 0xbe, 0x72, 0x51,
	0x49, 0xec, 0x0f, 0x04, 0xc4, 0xa3, 0x1c, 0x95, 0x71, 0x15, 0x4a, 0x07, 0x3d, 0xa4, 0xae, 0xff,
	0xa4, 0xc0, 0x72, 0xf6, 0xbd, 0x14, 0x0e, 0xa3, 0xe7, 0xa6, 0x89, 0x96, 0xb0, 0x06, 0x65, 0xb3,
	0x3f, 0x46, 0x8a, 0x58, 0x1c, 0xef, 0x8d, 0x51, 0x49, 0x9c, 0xf5, 0x59, 0x77, 0x8c, 0xca, 0x62,
	0xf5, 0x8d, 0x69, 0x8e, 0x91, 0x2a, 0x4a, 0x7b, 0x41, 0x27, 0x47, 0xcc, 0x3e, 0xa5, 0x1c, 0x55,
	0x84, 0x39, 0x62, 0xce, 0x64, 0x1e, 0x0a, 0xd7, 0xaa, 0xbc, 0x51, 0xaf, 0xb3, 0xbb, 0xb5, 0xbb,
	0x85, 0x34, 0x79, 0x0b, 0x97, 0xce, 0xa8, 0x17, 0x1e, 0xed, 0x20, 0x5d, 0x5c, 0x70, 0x38, 0xe8,
	0x6f, 0x3d, 0xda, 0x46, 0x35, 0x7c, 0x1b, 0xf0, 0xb1, 0x77, 0xea, 0xb1, 0xf3, 0x71, 0xa6, 0x16,
	0x64, 0xaf, 0xbf, 0x04, 0x5d, 0x50, 0x2d, 0x2b, 0xd3, 0xa0, 0x3c, 0x3c, 0x10, 0x85, 0xd5, 0xa0,
	0xf2, 0x6c, 0xff, 0xb0, 0x6b, 0x46, 0xd7, 0x33, 0x07, 0xdf, 0x99, 0x51, 0x6d, 0x7b, 0x5d, 0x73,
	0x10, 0xd5, 0xd6, 0x3b, 0x3c, 0xdc, 0x47, 0xaa, 0x58, 0x0d, 0x0e, 0x8e, 0x47, 0xa8, 0x22, 0x72,
	0x1d, 0x99, 0xe4, 0xb8, 0x6f, 0xa2, 0xaa, 0x70, 0xef, 0x12, 0xd2, 0xfd, 0x1e, 0x69, 0x9d, 0xdf,
	0x15, 0x00, 0xe2, 0xdb, 0xc9, 0x20, 0x46, 0x01, 0x15, 0x87, 0x4f, 0xfc, 0xf1, 0xdf, 0x4e, 0xa7,
	0x72, 0xc0, 0x6b, 0x3c, 0xbc, 0xe1, 0x14, 0xdb, 0x5a, 0x2a, 0xa6, 0x11, 0x32, 0x7b, 0x67, 0x9a,
	0xcc, 0x2c, 0xfa, 0xce, 0x34, 0x59, 0xbd, 0xb6, 0x96, 0x7a, 0x9f, 0xfd, 0xb0, 0x7d, 0xe2, 0xf2,
	0xd7, 0xf3, 0x49, 0xdb, 0x66, 0xb3, 0xcd, 0x73, 0xd7, 0xb3, 0x37, 0xa6, 0xae, 0x77, 0xba, 0x49,
	0x9d, 0x13, 0xba, 0x11, 0x45, 0xd9, 0x90, 0xad, 0xdf, 0xcc, 0x85, 0x9c, 0x54, 0xe5, 0xe6, 0xe3,
	0xbf, 0x02, 0x00, 0x00, 0xff, 0xff, 0xfa, 0x0f, 0xbb, 0xe7, 0xab, 0x0c, 0x00, 0x00,
}
