// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: cloudinstance/cloudinstance.proto

package cloudinstance

import (
	drivercommon "github.com/winc-link/edge-driver-proto/drivercommon"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CloudInstanceStatus int32

const (
	CloudInstanceStatus_Stop  CloudInstanceStatus = 0
	CloudInstanceStatus_Start CloudInstanceStatus = 1
	CloudInstanceStatus_Error CloudInstanceStatus = 2
)

// Enum value maps for CloudInstanceStatus.
var (
	CloudInstanceStatus_name = map[int32]string{
		0: "Stop",
		1: "Start",
		2: "Error",
	}
	CloudInstanceStatus_value = map[string]int32{
		"Stop":  0,
		"Start": 1,
		"Error": 2,
	}
)

func (x CloudInstanceStatus) Enum() *CloudInstanceStatus {
	p := new(CloudInstanceStatus)
	*p = x
	return p
}

func (x CloudInstanceStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CloudInstanceStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_cloudinstance_cloudinstance_proto_enumTypes[0].Descriptor()
}

func (CloudInstanceStatus) Type() protoreflect.EnumType {
	return &file_cloudinstance_cloudinstance_proto_enumTypes[0]
}

func (x CloudInstanceStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CloudInstanceStatus.Descriptor instead.
func (CloudInstanceStatus) EnumDescriptor() ([]byte, []int) {
	return file_cloudinstance_cloudinstance_proto_rawDescGZIP(), []int{0}
}

type QueryCloudInstanceByPlatformRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	IotPlatform   drivercommon.IotPlatform `protobuf:"varint,1,opt,name=iotPlatform,proto3,enum=drivercommon.IotPlatform" json:"iotPlatform,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryCloudInstanceByPlatformRequest) Reset() {
	*x = QueryCloudInstanceByPlatformRequest{}
	mi := &file_cloudinstance_cloudinstance_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryCloudInstanceByPlatformRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryCloudInstanceByPlatformRequest) ProtoMessage() {}

func (x *QueryCloudInstanceByPlatformRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cloudinstance_cloudinstance_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryCloudInstanceByPlatformRequest.ProtoReflect.Descriptor instead.
func (*QueryCloudInstanceByPlatformRequest) Descriptor() ([]byte, []int) {
	return file_cloudinstance_cloudinstance_proto_rawDescGZIP(), []int{0}
}

func (x *QueryCloudInstanceByPlatformRequest) GetIotPlatform() drivercommon.IotPlatform {
	if x != nil {
		return x.IotPlatform
	}
	return drivercommon.IotPlatform(0)
}

type QueryCloudInstanceByPlatformResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	CloudInstanceId   string                 `protobuf:"bytes,1,opt,name=CloudInstanceId,proto3" json:"CloudInstanceId,omitempty"`
	Address           string                 `protobuf:"bytes,2,opt,name=Address,proto3" json:"Address,omitempty"`
	CloudInstanceName string                 `protobuf:"bytes,3,opt,name=CloudInstanceName,proto3" json:"CloudInstanceName,omitempty"`
	Status            CloudInstanceStatus    `protobuf:"varint,4,opt,name=status,proto3,enum=cloudinstance.CloudInstanceStatus" json:"status,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *QueryCloudInstanceByPlatformResponse) Reset() {
	*x = QueryCloudInstanceByPlatformResponse{}
	mi := &file_cloudinstance_cloudinstance_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryCloudInstanceByPlatformResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryCloudInstanceByPlatformResponse) ProtoMessage() {}

func (x *QueryCloudInstanceByPlatformResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cloudinstance_cloudinstance_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryCloudInstanceByPlatformResponse.ProtoReflect.Descriptor instead.
func (*QueryCloudInstanceByPlatformResponse) Descriptor() ([]byte, []int) {
	return file_cloudinstance_cloudinstance_proto_rawDescGZIP(), []int{1}
}

func (x *QueryCloudInstanceByPlatformResponse) GetCloudInstanceId() string {
	if x != nil {
		return x.CloudInstanceId
	}
	return ""
}

func (x *QueryCloudInstanceByPlatformResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *QueryCloudInstanceByPlatformResponse) GetCloudInstanceName() string {
	if x != nil {
		return x.CloudInstanceName
	}
	return ""
}

func (x *QueryCloudInstanceByPlatformResponse) GetStatus() CloudInstanceStatus {
	if x != nil {
		return x.Status
	}
	return CloudInstanceStatus_Stop
}

type DriverReportPlatformInfoRequest struct {
	state            protoimpl.MessageState   `protogen:"open.v1"`
	DriverInstanceId string                   `protobuf:"bytes,1,opt,name=driverInstanceId,proto3" json:"driverInstanceId,omitempty"`
	IotPlatform      drivercommon.IotPlatform `protobuf:"varint,2,opt,name=iotPlatform,proto3,enum=drivercommon.IotPlatform" json:"iotPlatform,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DriverReportPlatformInfoRequest) Reset() {
	*x = DriverReportPlatformInfoRequest{}
	mi := &file_cloudinstance_cloudinstance_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverReportPlatformInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverReportPlatformInfoRequest) ProtoMessage() {}

func (x *DriverReportPlatformInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cloudinstance_cloudinstance_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverReportPlatformInfoRequest.ProtoReflect.Descriptor instead.
func (*DriverReportPlatformInfoRequest) Descriptor() ([]byte, []int) {
	return file_cloudinstance_cloudinstance_proto_rawDescGZIP(), []int{2}
}

func (x *DriverReportPlatformInfoRequest) GetDriverInstanceId() string {
	if x != nil {
		return x.DriverInstanceId
	}
	return ""
}

func (x *DriverReportPlatformInfoRequest) GetIotPlatform() drivercommon.IotPlatform {
	if x != nil {
		return x.IotPlatform
	}
	return drivercommon.IotPlatform(0)
}

type DriverReportPlatformInfoResponse struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	BaseResponse  *drivercommon.CommonResponse `protobuf:"bytes,1,opt,name=baseResponse,proto3" json:"baseResponse,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverReportPlatformInfoResponse) Reset() {
	*x = DriverReportPlatformInfoResponse{}
	mi := &file_cloudinstance_cloudinstance_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverReportPlatformInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverReportPlatformInfoResponse) ProtoMessage() {}

func (x *DriverReportPlatformInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cloudinstance_cloudinstance_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverReportPlatformInfoResponse.ProtoReflect.Descriptor instead.
func (*DriverReportPlatformInfoResponse) Descriptor() ([]byte, []int) {
	return file_cloudinstance_cloudinstance_proto_rawDescGZIP(), []int{3}
}

func (x *DriverReportPlatformInfoResponse) GetBaseResponse() *drivercommon.CommonResponse {
	if x != nil {
		return x.BaseResponse
	}
	return nil
}

var File_cloudinstance_cloudinstance_proto protoreflect.FileDescriptor

const file_cloudinstance_cloudinstance_proto_rawDesc = "" +
	"\n" +
	"!cloudinstance/cloudinstance.proto\x12\rcloudinstance\x1a\x19drivercommon/common.proto\"b\n" +
	"#QueryCloudInstanceByPlatformRequest\x12;\n" +
	"\viotPlatform\x18\x01 \x01(\x0e2\x19.drivercommon.IotPlatformR\viotPlatform\"\xd4\x01\n" +
	"$QueryCloudInstanceByPlatformResponse\x12(\n" +
	"\x0fCloudInstanceId\x18\x01 \x01(\tR\x0fCloudInstanceId\x12\x18\n" +
	"\aAddress\x18\x02 \x01(\tR\aAddress\x12,\n" +
	"\x11CloudInstanceName\x18\x03 \x01(\tR\x11CloudInstanceName\x12:\n" +
	"\x06status\x18\x04 \x01(\x0e2\".cloudinstance.CloudInstanceStatusR\x06status\"\x8a\x01\n" +
	"\x1fDriverReportPlatformInfoRequest\x12*\n" +
	"\x10driverInstanceId\x18\x01 \x01(\tR\x10driverInstanceId\x12;\n" +
	"\viotPlatform\x18\x02 \x01(\x0e2\x19.drivercommon.IotPlatformR\viotPlatform\"d\n" +
	" DriverReportPlatformInfoResponse\x12@\n" +
	"\fbaseResponse\x18\x01 \x01(\v2\x1c.drivercommon.CommonResponseR\fbaseResponse*5\n" +
	"\x13CloudInstanceStatus\x12\b\n" +
	"\x04Stop\x10\x00\x12\t\n" +
	"\x05Start\x10\x01\x12\t\n" +
	"\x05Error\x10\x022\xa1\x02\n" +
	"\x14CloudInstanceService\x12\x89\x01\n" +
	"\x1cQueryCloudInstanceByPlatform\x122.cloudinstance.QueryCloudInstanceByPlatformRequest\x1a3.cloudinstance.QueryCloudInstanceByPlatformResponse\"\x00\x12}\n" +
	"\x18DriverReportPlatformInfo\x12..cloudinstance.DriverReportPlatformInfoRequest\x1a/.cloudinstance.DriverReportPlatformInfoResponse\"\x00B6Z4github.com/winc-link/edge-driver-proto/cloudinstanceb\x06proto3"

var (
	file_cloudinstance_cloudinstance_proto_rawDescOnce sync.Once
	file_cloudinstance_cloudinstance_proto_rawDescData []byte
)

func file_cloudinstance_cloudinstance_proto_rawDescGZIP() []byte {
	file_cloudinstance_cloudinstance_proto_rawDescOnce.Do(func() {
		file_cloudinstance_cloudinstance_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cloudinstance_cloudinstance_proto_rawDesc), len(file_cloudinstance_cloudinstance_proto_rawDesc)))
	})
	return file_cloudinstance_cloudinstance_proto_rawDescData
}

var file_cloudinstance_cloudinstance_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cloudinstance_cloudinstance_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_cloudinstance_cloudinstance_proto_goTypes = []any{
	(CloudInstanceStatus)(0),                     // 0: cloudinstance.CloudInstanceStatus
	(*QueryCloudInstanceByPlatformRequest)(nil),  // 1: cloudinstance.QueryCloudInstanceByPlatformRequest
	(*QueryCloudInstanceByPlatformResponse)(nil), // 2: cloudinstance.QueryCloudInstanceByPlatformResponse
	(*DriverReportPlatformInfoRequest)(nil),      // 3: cloudinstance.DriverReportPlatformInfoRequest
	(*DriverReportPlatformInfoResponse)(nil),     // 4: cloudinstance.DriverReportPlatformInfoResponse
	(drivercommon.IotPlatform)(0),                // 5: drivercommon.IotPlatform
	(*drivercommon.CommonResponse)(nil),          // 6: drivercommon.CommonResponse
}
var file_cloudinstance_cloudinstance_proto_depIdxs = []int32{
	5, // 0: cloudinstance.QueryCloudInstanceByPlatformRequest.iotPlatform:type_name -> drivercommon.IotPlatform
	0, // 1: cloudinstance.QueryCloudInstanceByPlatformResponse.status:type_name -> cloudinstance.CloudInstanceStatus
	5, // 2: cloudinstance.DriverReportPlatformInfoRequest.iotPlatform:type_name -> drivercommon.IotPlatform
	6, // 3: cloudinstance.DriverReportPlatformInfoResponse.baseResponse:type_name -> drivercommon.CommonResponse
	1, // 4: cloudinstance.CloudInstanceService.QueryCloudInstanceByPlatform:input_type -> cloudinstance.QueryCloudInstanceByPlatformRequest
	3, // 5: cloudinstance.CloudInstanceService.DriverReportPlatformInfo:input_type -> cloudinstance.DriverReportPlatformInfoRequest
	2, // 6: cloudinstance.CloudInstanceService.QueryCloudInstanceByPlatform:output_type -> cloudinstance.QueryCloudInstanceByPlatformResponse
	4, // 7: cloudinstance.CloudInstanceService.DriverReportPlatformInfo:output_type -> cloudinstance.DriverReportPlatformInfoResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_cloudinstance_cloudinstance_proto_init() }
func file_cloudinstance_cloudinstance_proto_init() {
	if File_cloudinstance_cloudinstance_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cloudinstance_cloudinstance_proto_rawDesc), len(file_cloudinstance_cloudinstance_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cloudinstance_cloudinstance_proto_goTypes,
		DependencyIndexes: file_cloudinstance_cloudinstance_proto_depIdxs,
		EnumInfos:         file_cloudinstance_cloudinstance_proto_enumTypes,
		MessageInfos:      file_cloudinstance_cloudinstance_proto_msgTypes,
	}.Build()
	File_cloudinstance_cloudinstance_proto = out.File
	file_cloudinstance_cloudinstance_proto_goTypes = nil
	file_cloudinstance_cloudinstance_proto_depIdxs = nil
}
