// Code generated by protoc-gen-go. DO NOT EDIT.
// source: drivercommon/common.proto

package drivercommon

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/protobuf/types/known/emptypb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type IotPlatform int32

const (
	IotPlatform_LocalIot    IotPlatform = 0
	IotPlatform_CustomerIot IotPlatform = 1
	IotPlatform_WinCLinkIot IotPlatform = 2
	IotPlatform_AliIot      IotPlatform = 3
	IotPlatform_HuaweiIot   IotPlatform = 4
	IotPlatform_TencentIot  IotPlatform = 5
	IotPlatform_TuyaIot     IotPlatform = 6
	IotPlatform_OneNetIot   IotPlatform = 7
)

var IotPlatform_name = map[int32]string{
	0: "LocalIot",
	1: "CustomerIot",
	2: "WinCLinkIot",
	3: "AliIot",
	4: "HuaweiIot",
	5: "TencentIot",
	6: "TuyaIot",
	7: "OneNetIot",
}

var IotPlatform_value = map[string]int32{
	"LocalIot":    0,
	"CustomerIot": 1,
	"WinCLinkIot": 2,
	"AliIot":      3,
	"HuaweiIot":   4,
	"TencentIot":  5,
	"TuyaIot":     6,
	"OneNetIot":   7,
}

func (x IotPlatform) String() string {
	return proto.EnumName(IotPlatform_name, int32(x))
}

func (IotPlatform) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c20f641e39ad35ce, []int{0}
}

type MetaBasesType int32

const (
	MetaBasesType_Mysql  MetaBasesType = 0
	MetaBasesType_Sqlite MetaBasesType = 1
)

var MetaBasesType_name = map[int32]string{
	0: "Mysql",
	1: "Sqlite",
}

var MetaBasesType_value = map[string]int32{
	"Mysql":  0,
	"Sqlite": 1,
}

func (x MetaBasesType) String() string {
	return proto.EnumName(MetaBasesType_name, int32(x))
}

func (MetaBasesType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c20f641e39ad35ce, []int{1}
}

type CloudInstanceInfo struct {
	CloudInstanceId      string      `protobuf:"bytes,2,opt,name=cloudInstanceId,proto3" json:"cloudInstanceId,omitempty"`
	BaseAddress          string      `protobuf:"bytes,3,opt,name=baseAddress,proto3" json:"baseAddress,omitempty"`
	CloudInstanceName    string      `protobuf:"bytes,4,opt,name=cloudInstanceName,proto3" json:"cloudInstanceName,omitempty"`
	IotPlatform          IotPlatform `protobuf:"varint,5,opt,name=iotPlatform,proto3,enum=drivercommon.IotPlatform" json:"iotPlatform,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CloudInstanceInfo) Reset()         { *m = CloudInstanceInfo{} }
func (m *CloudInstanceInfo) String() string { return proto.CompactTextString(m) }
func (*CloudInstanceInfo) ProtoMessage()    {}
func (*CloudInstanceInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_c20f641e39ad35ce, []int{0}
}

func (m *CloudInstanceInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloudInstanceInfo.Unmarshal(m, b)
}
func (m *CloudInstanceInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloudInstanceInfo.Marshal(b, m, deterministic)
}
func (m *CloudInstanceInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloudInstanceInfo.Merge(m, src)
}
func (m *CloudInstanceInfo) XXX_Size() int {
	return xxx_messageInfo_CloudInstanceInfo.Size(m)
}
func (m *CloudInstanceInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_CloudInstanceInfo.DiscardUnknown(m)
}

var xxx_messageInfo_CloudInstanceInfo proto.InternalMessageInfo

func (m *CloudInstanceInfo) GetCloudInstanceId() string {
	if m != nil {
		return m.CloudInstanceId
	}
	return ""
}

func (m *CloudInstanceInfo) GetBaseAddress() string {
	if m != nil {
		return m.BaseAddress
	}
	return ""
}

func (m *CloudInstanceInfo) GetCloudInstanceName() string {
	if m != nil {
		return m.CloudInstanceName
	}
	return ""
}

func (m *CloudInstanceInfo) GetIotPlatform() IotPlatform {
	if m != nil {
		return m.IotPlatform
	}
	return IotPlatform_LocalIot
}

type BaseRequestMessage struct {
	UseCloudPlatform     bool               `protobuf:"varint,1,opt,name=useCloudPlatform,proto3" json:"useCloudPlatform,omitempty"`
	CloudInstanceInfo    *CloudInstanceInfo `protobuf:"bytes,2,opt,name=cloudInstanceInfo,proto3" json:"cloudInstanceInfo,omitempty"`
	DriverInstanceId     string             `protobuf:"bytes,3,opt,name=driverInstanceId,proto3" json:"driverInstanceId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *BaseRequestMessage) Reset()         { *m = BaseRequestMessage{} }
func (m *BaseRequestMessage) String() string { return proto.CompactTextString(m) }
func (*BaseRequestMessage) ProtoMessage()    {}
func (*BaseRequestMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_c20f641e39ad35ce, []int{1}
}

func (m *BaseRequestMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseRequestMessage.Unmarshal(m, b)
}
func (m *BaseRequestMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseRequestMessage.Marshal(b, m, deterministic)
}
func (m *BaseRequestMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseRequestMessage.Merge(m, src)
}
func (m *BaseRequestMessage) XXX_Size() int {
	return xxx_messageInfo_BaseRequestMessage.Size(m)
}
func (m *BaseRequestMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseRequestMessage.DiscardUnknown(m)
}

var xxx_messageInfo_BaseRequestMessage proto.InternalMessageInfo

func (m *BaseRequestMessage) GetUseCloudPlatform() bool {
	if m != nil {
		return m.UseCloudPlatform
	}
	return false
}

func (m *BaseRequestMessage) GetCloudInstanceInfo() *CloudInstanceInfo {
	if m != nil {
		return m.CloudInstanceInfo
	}
	return nil
}

func (m *BaseRequestMessage) GetDriverInstanceId() string {
	if m != nil {
		return m.DriverInstanceId
	}
	return ""
}

type CommonResponse struct {
	RequestId            string   `protobuf:"bytes,1,opt,name=RequestId,proto3" json:"RequestId,omitempty"`
	ErrorMessage         string   `protobuf:"bytes,2,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	Code                 string   `protobuf:"bytes,3,opt,name=Code,proto3" json:"Code,omitempty"`
	Success              bool     `protobuf:"varint,4,opt,name=Success,proto3" json:"Success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommonResponse) Reset()         { *m = CommonResponse{} }
func (m *CommonResponse) String() string { return proto.CompactTextString(m) }
func (*CommonResponse) ProtoMessage()    {}
func (*CommonResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c20f641e39ad35ce, []int{2}
}

func (m *CommonResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommonResponse.Unmarshal(m, b)
}
func (m *CommonResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommonResponse.Marshal(b, m, deterministic)
}
func (m *CommonResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommonResponse.Merge(m, src)
}
func (m *CommonResponse) XXX_Size() int {
	return xxx_messageInfo_CommonResponse.Size(m)
}
func (m *CommonResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CommonResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CommonResponse proto.InternalMessageInfo

func (m *CommonResponse) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *CommonResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *CommonResponse) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *CommonResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type Pong struct {
	Timestamp            string   `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pong) Reset()         { *m = Pong{} }
func (m *Pong) String() string { return proto.CompactTextString(m) }
func (*Pong) ProtoMessage()    {}
func (*Pong) Descriptor() ([]byte, []int) {
	return fileDescriptor_c20f641e39ad35ce, []int{3}
}

func (m *Pong) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pong.Unmarshal(m, b)
}
func (m *Pong) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pong.Marshal(b, m, deterministic)
}
func (m *Pong) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pong.Merge(m, src)
}
func (m *Pong) XXX_Size() int {
	return xxx_messageInfo_Pong.Size(m)
}
func (m *Pong) XXX_DiscardUnknown() {
	xxx_messageInfo_Pong.DiscardUnknown(m)
}

var xxx_messageInfo_Pong proto.InternalMessageInfo

func (m *Pong) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

type VersionResponse struct {
	Version              string   `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VersionResponse) Reset()         { *m = VersionResponse{} }
func (m *VersionResponse) String() string { return proto.CompactTextString(m) }
func (*VersionResponse) ProtoMessage()    {}
func (*VersionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c20f641e39ad35ce, []int{4}
}

func (m *VersionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VersionResponse.Unmarshal(m, b)
}
func (m *VersionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VersionResponse.Marshal(b, m, deterministic)
}
func (m *VersionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VersionResponse.Merge(m, src)
}
func (m *VersionResponse) XXX_Size() int {
	return xxx_messageInfo_VersionResponse.Size(m)
}
func (m *VersionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VersionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VersionResponse proto.InternalMessageInfo

func (m *VersionResponse) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type ConfigResponse struct {
	MetaBases            *MetaBases  `protobuf:"bytes,1,opt,name=metaBases,proto3" json:"metaBases,omitempty"`
	DataBases            *DataBases  `protobuf:"bytes,2,opt,name=dataBases,proto3" json:"dataBases,omitempty"`
	RedisBases           *RedisBases `protobuf:"bytes,3,opt,name=redisBases,proto3" json:"redisBases,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ConfigResponse) Reset()         { *m = ConfigResponse{} }
func (m *ConfigResponse) String() string { return proto.CompactTextString(m) }
func (*ConfigResponse) ProtoMessage()    {}
func (*ConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c20f641e39ad35ce, []int{5}
}

func (m *ConfigResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigResponse.Unmarshal(m, b)
}
func (m *ConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigResponse.Marshal(b, m, deterministic)
}
func (m *ConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigResponse.Merge(m, src)
}
func (m *ConfigResponse) XXX_Size() int {
	return xxx_messageInfo_ConfigResponse.Size(m)
}
func (m *ConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigResponse proto.InternalMessageInfo

func (m *ConfigResponse) GetMetaBases() *MetaBases {
	if m != nil {
		return m.MetaBases
	}
	return nil
}

func (m *ConfigResponse) GetDataBases() *DataBases {
	if m != nil {
		return m.DataBases
	}
	return nil
}

func (m *ConfigResponse) GetRedisBases() *RedisBases {
	if m != nil {
		return m.RedisBases
	}
	return nil
}

type MetaBases struct {
	Type                 MetaBasesType `protobuf:"varint,1,opt,name=Type,proto3,enum=drivercommon.MetaBasesType" json:"Type,omitempty"`
	Source               string        `protobuf:"bytes,2,opt,name=Source,proto3" json:"Source,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *MetaBases) Reset()         { *m = MetaBases{} }
func (m *MetaBases) String() string { return proto.CompactTextString(m) }
func (*MetaBases) ProtoMessage()    {}
func (*MetaBases) Descriptor() ([]byte, []int) {
	return fileDescriptor_c20f641e39ad35ce, []int{6}
}

func (m *MetaBases) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetaBases.Unmarshal(m, b)
}
func (m *MetaBases) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetaBases.Marshal(b, m, deterministic)
}
func (m *MetaBases) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetaBases.Merge(m, src)
}
func (m *MetaBases) XXX_Size() int {
	return xxx_messageInfo_MetaBases.Size(m)
}
func (m *MetaBases) XXX_DiscardUnknown() {
	xxx_messageInfo_MetaBases.DiscardUnknown(m)
}

var xxx_messageInfo_MetaBases proto.InternalMessageInfo

func (m *MetaBases) GetType() MetaBasesType {
	if m != nil {
		return m.Type
	}
	return MetaBasesType_Mysql
}

func (m *MetaBases) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

type DataBases struct {
	Type                 string          `protobuf:"bytes,1,opt,name=Type,proto3" json:"Type,omitempty"`
	Tdengine             *TDengineSource `protobuf:"bytes,2,opt,name=tdengine,proto3" json:"tdengine,omitempty"`
	InfluxDB             *InfluxDB       `protobuf:"bytes,3,opt,name=influxDB,proto3" json:"influxDB,omitempty"`
	ClickHouse           *ClickHouse     `protobuf:"bytes,4,opt,name=clickHouse,proto3" json:"clickHouse,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *DataBases) Reset()         { *m = DataBases{} }
func (m *DataBases) String() string { return proto.CompactTextString(m) }
func (*DataBases) ProtoMessage()    {}
func (*DataBases) Descriptor() ([]byte, []int) {
	return fileDescriptor_c20f641e39ad35ce, []int{7}
}

func (m *DataBases) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataBases.Unmarshal(m, b)
}
func (m *DataBases) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataBases.Marshal(b, m, deterministic)
}
func (m *DataBases) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataBases.Merge(m, src)
}
func (m *DataBases) XXX_Size() int {
	return xxx_messageInfo_DataBases.Size(m)
}
func (m *DataBases) XXX_DiscardUnknown() {
	xxx_messageInfo_DataBases.DiscardUnknown(m)
}

var xxx_messageInfo_DataBases proto.InternalMessageInfo

func (m *DataBases) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *DataBases) GetTdengine() *TDengineSource {
	if m != nil {
		return m.Tdengine
	}
	return nil
}

func (m *DataBases) GetInfluxDB() *InfluxDB {
	if m != nil {
		return m.InfluxDB
	}
	return nil
}

func (m *DataBases) GetClickHouse() *ClickHouse {
	if m != nil {
		return m.ClickHouse
	}
	return nil
}

type TDengineSource struct {
	Dsn                  string   `protobuf:"bytes,1,opt,name=Dsn,proto3" json:"Dsn,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TDengineSource) Reset()         { *m = TDengineSource{} }
func (m *TDengineSource) String() string { return proto.CompactTextString(m) }
func (*TDengineSource) ProtoMessage()    {}
func (*TDengineSource) Descriptor() ([]byte, []int) {
	return fileDescriptor_c20f641e39ad35ce, []int{8}
}

func (m *TDengineSource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TDengineSource.Unmarshal(m, b)
}
func (m *TDengineSource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TDengineSource.Marshal(b, m, deterministic)
}
func (m *TDengineSource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TDengineSource.Merge(m, src)
}
func (m *TDengineSource) XXX_Size() int {
	return xxx_messageInfo_TDengineSource.Size(m)
}
func (m *TDengineSource) XXX_DiscardUnknown() {
	xxx_messageInfo_TDengineSource.DiscardUnknown(m)
}

var xxx_messageInfo_TDengineSource proto.InternalMessageInfo

func (m *TDengineSource) GetDsn() string {
	if m != nil {
		return m.Dsn
	}
	return ""
}

type InfluxDB struct {
	Org                  string   `protobuf:"bytes,1,opt,name=org,proto3" json:"org,omitempty"`
	Bucket               string   `protobuf:"bytes,2,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Url                  string   `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Token                string   `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InfluxDB) Reset()         { *m = InfluxDB{} }
func (m *InfluxDB) String() string { return proto.CompactTextString(m) }
func (*InfluxDB) ProtoMessage()    {}
func (*InfluxDB) Descriptor() ([]byte, []int) {
	return fileDescriptor_c20f641e39ad35ce, []int{9}
}

func (m *InfluxDB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InfluxDB.Unmarshal(m, b)
}
func (m *InfluxDB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InfluxDB.Marshal(b, m, deterministic)
}
func (m *InfluxDB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InfluxDB.Merge(m, src)
}
func (m *InfluxDB) XXX_Size() int {
	return xxx_messageInfo_InfluxDB.Size(m)
}
func (m *InfluxDB) XXX_DiscardUnknown() {
	xxx_messageInfo_InfluxDB.DiscardUnknown(m)
}

var xxx_messageInfo_InfluxDB proto.InternalMessageInfo

func (m *InfluxDB) GetOrg() string {
	if m != nil {
		return m.Org
	}
	return ""
}

func (m *InfluxDB) GetBucket() string {
	if m != nil {
		return m.Bucket
	}
	return ""
}

func (m *InfluxDB) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *InfluxDB) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type ClickHouse struct {
	Addr                 []string `protobuf:"bytes,1,rep,name=addr,proto3" json:"addr,omitempty"`
	Database             string   `protobuf:"bytes,2,opt,name=database,proto3" json:"database,omitempty"`
	Username             string   `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClickHouse) Reset()         { *m = ClickHouse{} }
func (m *ClickHouse) String() string { return proto.CompactTextString(m) }
func (*ClickHouse) ProtoMessage()    {}
func (*ClickHouse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c20f641e39ad35ce, []int{10}
}

func (m *ClickHouse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClickHouse.Unmarshal(m, b)
}
func (m *ClickHouse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClickHouse.Marshal(b, m, deterministic)
}
func (m *ClickHouse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClickHouse.Merge(m, src)
}
func (m *ClickHouse) XXX_Size() int {
	return xxx_messageInfo_ClickHouse.Size(m)
}
func (m *ClickHouse) XXX_DiscardUnknown() {
	xxx_messageInfo_ClickHouse.DiscardUnknown(m)
}

var xxx_messageInfo_ClickHouse proto.InternalMessageInfo

func (m *ClickHouse) GetAddr() []string {
	if m != nil {
		return m.Addr
	}
	return nil
}

func (m *ClickHouse) GetDatabase() string {
	if m != nil {
		return m.Database
	}
	return ""
}

func (m *ClickHouse) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *ClickHouse) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type RedisBases struct {
	Address              string   `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	DB                   int32    `protobuf:"varint,3,opt,name=DB,proto3" json:"DB,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RedisBases) Reset()         { *m = RedisBases{} }
func (m *RedisBases) String() string { return proto.CompactTextString(m) }
func (*RedisBases) ProtoMessage()    {}
func (*RedisBases) Descriptor() ([]byte, []int) {
	return fileDescriptor_c20f641e39ad35ce, []int{11}
}

func (m *RedisBases) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RedisBases.Unmarshal(m, b)
}
func (m *RedisBases) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RedisBases.Marshal(b, m, deterministic)
}
func (m *RedisBases) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RedisBases.Merge(m, src)
}
func (m *RedisBases) XXX_Size() int {
	return xxx_messageInfo_RedisBases.Size(m)
}
func (m *RedisBases) XXX_DiscardUnknown() {
	xxx_messageInfo_RedisBases.DiscardUnknown(m)
}

var xxx_messageInfo_RedisBases proto.InternalMessageInfo

func (m *RedisBases) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *RedisBases) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *RedisBases) GetDB() int32 {
	if m != nil {
		return m.DB
	}
	return 0
}

func init() {
	proto.RegisterEnum("drivercommon.IotPlatform", IotPlatform_name, IotPlatform_value)
	proto.RegisterEnum("drivercommon.MetaBasesType", MetaBasesType_name, MetaBasesType_value)
	proto.RegisterType((*CloudInstanceInfo)(nil), "drivercommon.CloudInstanceInfo")
	proto.RegisterType((*BaseRequestMessage)(nil), "drivercommon.BaseRequestMessage")
	proto.RegisterType((*CommonResponse)(nil), "drivercommon.CommonResponse")
	proto.RegisterType((*Pong)(nil), "drivercommon.Pong")
	proto.RegisterType((*VersionResponse)(nil), "drivercommon.VersionResponse")
	proto.RegisterType((*ConfigResponse)(nil), "drivercommon.ConfigResponse")
	proto.RegisterType((*MetaBases)(nil), "drivercommon.MetaBases")
	proto.RegisterType((*DataBases)(nil), "drivercommon.DataBases")
	proto.RegisterType((*TDengineSource)(nil), "drivercommon.TDengineSource")
	proto.RegisterType((*InfluxDB)(nil), "drivercommon.InfluxDB")
	proto.RegisterType((*ClickHouse)(nil), "drivercommon.ClickHouse")
	proto.RegisterType((*RedisBases)(nil), "drivercommon.RedisBases")
}

func init() { proto.RegisterFile("drivercommon/common.proto", fileDescriptor_c20f641e39ad35ce) }

var fileDescriptor_c20f641e39ad35ce = []byte{
	// 884 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x55, 0xdd, 0x6a, 0xe3, 0x46,
	0x14, 0x8e, 0xfc, 0xaf, 0xe3, 0xac, 0xe3, 0x1d, 0x96, 0xd4, 0x9b, 0xdd, 0x52, 0x23, 0x4a, 0x09,
	0x69, 0x63, 0x83, 0xb7, 0x0b, 0x0b, 0xbd, 0x5a, 0xdb, 0xa5, 0x31, 0x6c, 0xd2, 0xa0, 0x98, 0x16,
	0x4a, 0x6f, 0x64, 0xe9, 0x58, 0x1d, 0x2c, 0xcd, 0x38, 0x33, 0xa3, 0x4d, 0x73, 0xd7, 0x8b, 0x3e,
	0x54, 0xa1, 0x0f, 0x50, 0xe8, 0x65, 0x9f, 0xa8, 0x8c, 0x34, 0x92, 0x25, 0x7b, 0x73, 0xe5, 0x39,
	0xe7, 0xfb, 0xbe, 0xf3, 0x37, 0xe3, 0x23, 0x78, 0x19, 0x08, 0xfa, 0x11, 0x85, 0xcf, 0xe3, 0x98,
	0xb3, 0x71, 0xf6, 0x33, 0xda, 0x0a, 0xae, 0x38, 0x39, 0x2e, 0x43, 0x67, 0xaf, 0x42, 0xce, 0xc3,
	0x08, 0xc7, 0x29, 0xb6, 0x4a, 0xd6, 0x63, 0x8c, 0xb7, 0xea, 0x31, 0xa3, 0x3a, 0xff, 0x5a, 0xf0,
	0x7c, 0x16, 0xf1, 0x24, 0x58, 0x30, 0xa9, 0x3c, 0xe6, 0xe3, 0x82, 0xad, 0x39, 0x39, 0x87, 0x13,
	0xbf, 0xe2, 0x0c, 0x06, 0xb5, 0xa1, 0x75, 0x6e, 0xbb, 0xfb, 0x6e, 0x32, 0x84, 0xee, 0xca, 0x93,
	0xf8, 0x3e, 0x08, 0x04, 0x4a, 0x39, 0xa8, 0xa7, 0xac, 0xb2, 0x8b, 0x7c, 0x03, 0xcf, 0x2b, 0xa2,
	0x1b, 0x2f, 0xc6, 0x41, 0x23, 0xe5, 0x1d, 0x02, 0xe4, 0x3b, 0xe8, 0x52, 0xae, 0x6e, 0x23, 0x4f,
	0xad, 0xb9, 0x88, 0x07, 0xcd, 0xa1, 0x75, 0xde, 0x9b, 0xbc, 0x1c, 0x95, 0x1b, 0x1a, 0x2d, 0x76,
	0x04, 0xb7, 0xcc, 0x76, 0xfe, 0xb6, 0x80, 0x4c, 0x3d, 0x89, 0x2e, 0xde, 0x27, 0x28, 0xd5, 0x35,
	0x4a, 0xe9, 0x85, 0x48, 0x2e, 0xa0, 0x9f, 0x48, 0x4c, 0xbb, 0x2c, 0x02, 0x5b, 0x43, 0xeb, 0xbc,
	0xe3, 0x1e, 0xf8, 0xc9, 0xf5, 0x5e, 0xb5, 0x7a, 0x1c, 0x69, 0xef, 0xdd, 0xc9, 0x17, 0xd5, 0x2a,
	0x0e, 0xa6, 0xe6, 0x1e, 0x2a, 0x75, 0xea, 0x4c, 0x54, 0x9a, 0x64, 0x36, 0xa3, 0x03, 0xbf, 0xf3,
	0x87, 0x05, 0xbd, 0x59, 0x1a, 0xdb, 0x45, 0xb9, 0xe5, 0x4c, 0x22, 0x79, 0x0d, 0xb6, 0xe9, 0x65,
	0x11, 0xa4, 0x25, 0xdb, 0xee, 0xce, 0x41, 0x1c, 0x38, 0x46, 0x21, 0xb8, 0x30, 0x7d, 0x9a, 0x2b,
	0xaa, 0xf8, 0x08, 0x81, 0xc6, 0x8c, 0x07, 0x68, 0x92, 0xa6, 0x67, 0x32, 0x80, 0xf6, 0x5d, 0xe2,
	0xfb, 0xfa, 0xbe, 0x1a, 0xe9, 0x18, 0x72, 0xd3, 0xf9, 0x12, 0x1a, 0xb7, 0x9c, 0x85, 0x3a, 0xaf,
	0xa2, 0x31, 0x4a, 0xe5, 0xc5, 0x5b, 0x13, 0x76, 0xe7, 0x70, 0xbe, 0x86, 0x93, 0x9f, 0x50, 0x48,
	0x5a, 0x2a, 0x74, 0x00, 0xed, 0x8f, 0x99, 0xcb, 0xd0, 0x73, 0xd3, 0xf9, 0x2b, 0xed, 0x8a, 0xad,
	0x69, 0x58, 0x90, 0xdf, 0x82, 0x1d, 0xa3, 0xf2, 0xf4, 0x4d, 0xc9, 0xb4, 0xab, 0xee, 0xe4, 0xb3,
	0xea, 0x6c, 0xaf, 0x73, 0xd8, 0xdd, 0x31, 0xb5, 0x2c, 0xf0, 0x72, 0x59, 0xed, 0x53, 0xb2, 0xb9,
	0x57, 0xc8, 0x0a, 0x26, 0x79, 0x07, 0x20, 0x30, 0xa0, 0x32, 0xd3, 0xd5, 0x53, 0xdd, 0xa0, 0xaa,
	0x73, 0x0b, 0xdc, 0x2d, 0x71, 0x9d, 0x25, 0xd8, 0x45, 0x21, 0x64, 0x0c, 0x8d, 0xe5, 0xe3, 0x16,
	0xd3, 0x7a, 0x7b, 0x93, 0x57, 0x4f, 0xd4, 0xab, 0x29, 0x6e, 0x4a, 0x24, 0xa7, 0xd0, 0xba, 0xe3,
	0x89, 0xf0, 0xf3, 0x7b, 0x31, 0x96, 0xf3, 0x8f, 0x05, 0x76, 0x51, 0xa8, 0xbe, 0x9f, 0x22, 0xac,
	0x6d, 0x94, 0xef, 0xa0, 0xa3, 0x02, 0x64, 0x21, 0x65, 0x68, 0xfa, 0x7c, 0x5d, 0x4d, 0xb7, 0x9c,
	0x67, 0x68, 0x16, 0xd1, 0x2d, 0xd8, 0x64, 0x02, 0x1d, 0xca, 0xd6, 0x51, 0xf2, 0xfb, 0x7c, 0x6a,
	0x3a, 0x3d, 0xdd, 0xfb, 0xeb, 0x18, 0xd4, 0x2d, 0x78, 0x7a, 0x3e, 0x7e, 0x44, 0xfd, 0xcd, 0x15,
	0x4f, 0x64, 0xf6, 0xc7, 0x3c, 0x98, 0xcf, 0xac, 0xc0, 0xdd, 0x12, 0xd7, 0x71, 0xa0, 0x57, 0xad,
	0x84, 0xf4, 0xa1, 0x3e, 0x97, 0xcc, 0x34, 0xa3, 0x8f, 0xce, 0xaf, 0xd0, 0xc9, 0x73, 0x6a, 0x94,
	0x8b, 0x30, 0x47, 0xb9, 0x08, 0xf5, 0x8c, 0x56, 0x89, 0xbf, 0x41, 0x95, 0xcf, 0x28, 0xb3, 0x34,
	0x33, 0x11, 0x91, 0x79, 0xb4, 0xfa, 0x48, 0x5e, 0x40, 0x53, 0xf1, 0x0d, 0x32, 0xb3, 0x39, 0x32,
	0xc3, 0x51, 0x00, 0xbb, 0xda, 0xf4, 0x2c, 0xbd, 0x20, 0x10, 0x03, 0x6b, 0x58, 0xd7, 0xb3, 0xd4,
	0x67, 0x72, 0x06, 0x1d, 0xfd, 0x14, 0xf4, 0x42, 0x32, 0x39, 0x0a, 0x5b, 0x63, 0x89, 0x44, 0xc1,
	0xf4, 0x42, 0xca, 0x52, 0x15, 0xb6, 0xc6, 0xb6, 0x9e, 0x94, 0x0f, 0x5c, 0x04, 0x26, 0x65, 0x61,
	0x3b, 0x2e, 0xc0, 0xee, 0xc5, 0xe8, 0xa7, 0x9f, 0x6f, 0xbf, 0xac, 0xb3, 0xdc, 0xd4, 0x31, 0x6e,
	0xf3, 0x18, 0x26, 0x77, 0x6e, 0x93, 0x1e, 0xd4, 0xcc, 0x1d, 0x35, 0xdd, 0xda, 0x7c, 0x7a, 0xf1,
	0xa7, 0x05, 0xdd, 0xd2, 0x5e, 0x23, 0xc7, 0xd0, 0xf9, 0xc0, 0x7d, 0x2f, 0x5a, 0x70, 0xd5, 0x3f,
	0x22, 0x27, 0xd0, 0x9d, 0x25, 0x52, 0xf1, 0x18, 0x85, 0x76, 0x58, 0xda, 0xf1, 0x33, 0x65, 0xb3,
	0x0f, 0x94, 0x6d, 0xb4, 0xa3, 0x46, 0x00, 0x5a, 0xef, 0x23, 0xaa, 0xcf, 0x75, 0xf2, 0x0c, 0xec,
	0xab, 0xc4, 0x7b, 0xc0, 0xd4, 0x6c, 0x90, 0x1e, 0xc0, 0x12, 0x99, 0x8f, 0x4c, 0x69, 0xbb, 0x49,
	0xba, 0xd0, 0x5e, 0x26, 0x8f, 0x9e, 0x36, 0x5a, 0x9a, 0xfb, 0x23, 0xc3, 0x1b, 0x4c, 0xb1, 0xf6,
	0xc5, 0x57, 0xf0, 0xac, 0xf2, 0x96, 0x89, 0x0d, 0xcd, 0xeb, 0x47, 0x79, 0x1f, 0xf5, 0x8f, 0x74,
	0x8a, 0xbb, 0xfb, 0x88, 0x2a, 0xec, 0x5b, 0x93, 0xff, 0x2c, 0x68, 0x65, 0xbb, 0x8a, 0x7c, 0x0b,
	0x8d, 0x5b, 0xca, 0x42, 0x72, 0x3a, 0xca, 0xbe, 0x33, 0xa3, 0xfc, 0x3b, 0x33, 0xfa, 0x5e, 0x7f,
	0x67, 0xce, 0x48, 0xf5, 0x2d, 0xe9, 0xfd, 0xe2, 0x1c, 0x91, 0x29, 0xb4, 0xcd, 0x0e, 0x79, 0x52,
	0xf8, 0x79, 0x55, 0xb8, 0xb7, 0x72, 0x9c, 0x23, 0x72, 0x03, 0x2f, 0x7e, 0x40, 0x75, 0x95, 0xc4,
	0x31, 0x65, 0xe1, 0x8a, 0x8a, 0x20, 0xdb, 0x33, 0x4f, 0x06, 0xdc, 0xfb, 0x17, 0x55, 0xb7, 0x92,
	0x73, 0x34, 0x7d, 0xfb, 0xcb, 0x9b, 0x90, 0xaa, 0xdf, 0x92, 0xd5, 0xc8, 0xe7, 0xf1, 0xf8, 0x81,
	0x32, 0xff, 0x32, 0xa2, 0x6c, 0x33, 0xc6, 0x20, 0xc4, 0xcb, 0x4c, 0x7a, 0x99, 0x86, 0x1c, 0x97,
	0xe3, 0xac, 0x5a, 0xa9, 0xef, 0xcd, 0xff, 0x01, 0x00, 0x00, 0xff, 0xff, 0x98, 0x6a, 0xd5, 0xbd,
	0x91, 0x07, 0x00, 0x00,
}
