// Code generated by protoc-gen-go. DO NOT EDIT.
// source: thingmodel/thingmodel.proto

package thingmodel

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	drivercommon "github.com/winc-link/edge-driver-proto/drivercommon"
	_ "google.golang.org/protobuf/types/known/emptypb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type OperationType int32

const (
	OperationType_UNSPECIFIED OperationType = 0
	// 下发相关
	OperationType_PROPERTY_SET                     OperationType = 1
	OperationType_PROPERTY_GET                     OperationType = 2
	OperationType_SERVICE_EXECUTE                  OperationType = 3
	OperationType_PROPERTY_REPORT_RESPONSE         OperationType = 4
	OperationType_EVENT_REPORT_RESPONSE            OperationType = 5
	OperationType_DATA_BATCH_REPORT_RESPONSE       OperationType = 6
	OperationType_PROPERTY_DESIRED_GET_RESPONSE    OperationType = 7
	OperationType_PROPERTY_DESIRED_DELETE_RESPONSE OperationType = 8
	OperationType_CUSTOM_MQTT_PUBLISH              OperationType = 9
	// 上报相关
	OperationType_PROPERTY_REPORT          OperationType = 20
	OperationType_PROPERTY_SET_RESPONSE    OperationType = 21
	OperationType_PROPERTY_GET_RESPONSE    OperationType = 22
	OperationType_SERVICE_EXECUTE_RESPONSE OperationType = 23
	OperationType_EVENT_REPORT             OperationType = 24
	OperationType_DATA_BATCH_REPORT        OperationType = 25
	OperationType_PROPERTY_DESIRED_GET     OperationType = 26
	OperationType_PROPERTY_DESIRED_DELETE  OperationType = 27
)

var OperationType_name = map[int32]string{
	0:  "UNSPECIFIED",
	1:  "PROPERTY_SET",
	2:  "PROPERTY_GET",
	3:  "SERVICE_EXECUTE",
	4:  "PROPERTY_REPORT_RESPONSE",
	5:  "EVENT_REPORT_RESPONSE",
	6:  "DATA_BATCH_REPORT_RESPONSE",
	7:  "PROPERTY_DESIRED_GET_RESPONSE",
	8:  "PROPERTY_DESIRED_DELETE_RESPONSE",
	9:  "CUSTOM_MQTT_PUBLISH",
	20: "PROPERTY_REPORT",
	21: "PROPERTY_SET_RESPONSE",
	22: "PROPERTY_GET_RESPONSE",
	23: "SERVICE_EXECUTE_RESPONSE",
	24: "EVENT_REPORT",
	25: "DATA_BATCH_REPORT",
	26: "PROPERTY_DESIRED_GET",
	27: "PROPERTY_DESIRED_DELETE",
}

var OperationType_value = map[string]int32{
	"UNSPECIFIED":                      0,
	"PROPERTY_SET":                     1,
	"PROPERTY_GET":                     2,
	"SERVICE_EXECUTE":                  3,
	"PROPERTY_REPORT_RESPONSE":         4,
	"EVENT_REPORT_RESPONSE":            5,
	"DATA_BATCH_REPORT_RESPONSE":       6,
	"PROPERTY_DESIRED_GET_RESPONSE":    7,
	"PROPERTY_DESIRED_DELETE_RESPONSE": 8,
	"CUSTOM_MQTT_PUBLISH":              9,
	"PROPERTY_REPORT":                  20,
	"PROPERTY_SET_RESPONSE":            21,
	"PROPERTY_GET_RESPONSE":            22,
	"SERVICE_EXECUTE_RESPONSE":         23,
	"EVENT_REPORT":                     24,
	"DATA_BATCH_REPORT":                25,
	"PROPERTY_DESIRED_GET":             26,
	"PROPERTY_DESIRED_DELETE":          27,
}

func (x OperationType) String() string {
	return proto.EnumName(OperationType_name, int32(x))
}

func (OperationType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ab0ffa8f547ef1dd, []int{0}
}

// 物模型
type ThingModelMsg struct {
	BaseRequest          *drivercommon.BaseRequestMessage `protobuf:"bytes,1,opt,name=baseRequest,proto3" json:"baseRequest,omitempty"`
	DeviceId             string                           `protobuf:"bytes,2,opt,name=deviceId,proto3" json:"deviceId,omitempty"`
	OperationType        OperationType                    `protobuf:"varint,3,opt,name=operationType,proto3,enum=thingmodel.OperationType" json:"operationType,omitempty"`
	Data                 string                           `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *ThingModelMsg) Reset()         { *m = ThingModelMsg{} }
func (m *ThingModelMsg) String() string { return proto.CompactTextString(m) }
func (*ThingModelMsg) ProtoMessage()    {}
func (*ThingModelMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab0ffa8f547ef1dd, []int{0}
}

func (m *ThingModelMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThingModelMsg.Unmarshal(m, b)
}
func (m *ThingModelMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThingModelMsg.Marshal(b, m, deterministic)
}
func (m *ThingModelMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThingModelMsg.Merge(m, src)
}
func (m *ThingModelMsg) XXX_Size() int {
	return xxx_messageInfo_ThingModelMsg.Size(m)
}
func (m *ThingModelMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_ThingModelMsg.DiscardUnknown(m)
}

var xxx_messageInfo_ThingModelMsg proto.InternalMessageInfo

func (m *ThingModelMsg) GetBaseRequest() *drivercommon.BaseRequestMessage {
	if m != nil {
		return m.BaseRequest
	}
	return nil
}

func (m *ThingModelMsg) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

func (m *ThingModelMsg) GetOperationType() OperationType {
	if m != nil {
		return m.OperationType
	}
	return OperationType_UNSPECIFIED
}

func (m *ThingModelMsg) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type ThingModelIssueMsg struct {
	DeviceId             string        `protobuf:"bytes,1,opt,name=deviceId,proto3" json:"deviceId,omitempty"`
	OperationType        OperationType `protobuf:"varint,2,opt,name=operationType,proto3,enum=thingmodel.OperationType" json:"operationType,omitempty"`
	Data                 string        `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ThingModelIssueMsg) Reset()         { *m = ThingModelIssueMsg{} }
func (m *ThingModelIssueMsg) String() string { return proto.CompactTextString(m) }
func (*ThingModelIssueMsg) ProtoMessage()    {}
func (*ThingModelIssueMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab0ffa8f547ef1dd, []int{1}
}

func (m *ThingModelIssueMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThingModelIssueMsg.Unmarshal(m, b)
}
func (m *ThingModelIssueMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThingModelIssueMsg.Marshal(b, m, deterministic)
}
func (m *ThingModelIssueMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThingModelIssueMsg.Merge(m, src)
}
func (m *ThingModelIssueMsg) XXX_Size() int {
	return xxx_messageInfo_ThingModelIssueMsg.Size(m)
}
func (m *ThingModelIssueMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_ThingModelIssueMsg.DiscardUnknown(m)
}

var xxx_messageInfo_ThingModelIssueMsg proto.InternalMessageInfo

func (m *ThingModelIssueMsg) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

func (m *ThingModelIssueMsg) GetOperationType() OperationType {
	if m != nil {
		return m.OperationType
	}
	return OperationType_UNSPECIFIED
}

func (m *ThingModelIssueMsg) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type MessageRateResponse struct {
	MessageRate          []*MessageRate `protobuf:"bytes,1,rep,name=messageRate,proto3" json:"messageRate,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *MessageRateResponse) Reset()         { *m = MessageRateResponse{} }
func (m *MessageRateResponse) String() string { return proto.CompactTextString(m) }
func (*MessageRateResponse) ProtoMessage()    {}
func (*MessageRateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab0ffa8f547ef1dd, []int{2}
}

func (m *MessageRateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageRateResponse.Unmarshal(m, b)
}
func (m *MessageRateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageRateResponse.Marshal(b, m, deterministic)
}
func (m *MessageRateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageRateResponse.Merge(m, src)
}
func (m *MessageRateResponse) XXX_Size() int {
	return xxx_messageInfo_MessageRateResponse.Size(m)
}
func (m *MessageRateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageRateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MessageRateResponse proto.InternalMessageInfo

func (m *MessageRateResponse) GetMessageRate() []*MessageRate {
	if m != nil {
		return m.MessageRate
	}
	return nil
}

type MessageRate struct {
	T                    string   `protobuf:"bytes,1,opt,name=t,proto3" json:"t,omitempty"`
	UpQos                uint64   `protobuf:"varint,2,opt,name=upQos,proto3" json:"upQos,omitempty"`
	DownQos              uint64   `protobuf:"varint,3,opt,name=downQos,proto3" json:"downQos,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageRate) Reset()         { *m = MessageRate{} }
func (m *MessageRate) String() string { return proto.CompactTextString(m) }
func (*MessageRate) ProtoMessage()    {}
func (*MessageRate) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab0ffa8f547ef1dd, []int{3}
}

func (m *MessageRate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageRate.Unmarshal(m, b)
}
func (m *MessageRate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageRate.Marshal(b, m, deterministic)
}
func (m *MessageRate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageRate.Merge(m, src)
}
func (m *MessageRate) XXX_Size() int {
	return xxx_messageInfo_MessageRate.Size(m)
}
func (m *MessageRate) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageRate.DiscardUnknown(m)
}

var xxx_messageInfo_MessageRate proto.InternalMessageInfo

func (m *MessageRate) GetT() string {
	if m != nil {
		return m.T
	}
	return ""
}

func (m *MessageRate) GetUpQos() uint64 {
	if m != nil {
		return m.UpQos
	}
	return 0
}

func (m *MessageRate) GetDownQos() uint64 {
	if m != nil {
		return m.DownQos
	}
	return 0
}

func init() {
	proto.RegisterEnum("thingmodel.OperationType", OperationType_name, OperationType_value)
	proto.RegisterType((*ThingModelMsg)(nil), "thingmodel.ThingModelMsg")
	proto.RegisterType((*ThingModelIssueMsg)(nil), "thingmodel.ThingModelIssueMsg")
	proto.RegisterType((*MessageRateResponse)(nil), "thingmodel.MessageRateResponse")
	proto.RegisterType((*MessageRate)(nil), "thingmodel.MessageRate")
}

func init() { proto.RegisterFile("thingmodel/thingmodel.proto", fileDescriptor_ab0ffa8f547ef1dd) }

var fileDescriptor_ab0ffa8f547ef1dd = []byte{
	// 662 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0xdd, 0x6e, 0xda, 0x4c,
	0x10, 0x8d, 0x03, 0xf9, 0x1b, 0x92, 0x2f, 0xfe, 0x96, 0x10, 0x8c, 0x49, 0x53, 0x8a, 0x7a, 0x81,
	0x2a, 0xc5, 0xa8, 0xe4, 0xaa, 0x57, 0x55, 0x80, 0x6d, 0x63, 0x35, 0x06, 0x67, 0xbd, 0x44, 0x6d,
	0x2f, 0x8a, 0x00, 0x6f, 0x1d, 0xab, 0xc1, 0xeb, 0x62, 0x93, 0x28, 0x0f, 0xd0, 0x37, 0xeb, 0x6b,
	0xf4, 0x5d, 0x2a, 0x9b, 0x1a, 0xaf, 0x43, 0xa2, 0x4a, 0xbd, 0xb2, 0x77, 0xe6, 0xcc, 0xcc, 0x39,
	0xa3, 0x99, 0x81, 0x6a, 0x78, 0xed, 0x7a, 0xce, 0x94, 0xdb, 0xec, 0xa6, 0x99, 0xfe, 0x6a, 0xfe,
	0x8c, 0x87, 0x1c, 0x41, 0x6a, 0x51, 0xab, 0x0e, 0xe7, 0xce, 0x0d, 0x6b, 0xc6, 0x9e, 0xf1, 0xfc,
	0x6b, 0x93, 0x4d, 0xfd, 0xf0, 0x7e, 0x01, 0x54, 0x2b, 0xf6, 0xcc, 0xbd, 0x65, 0xb3, 0x09, 0x9f,
	0x4e, 0xb9, 0xd7, 0x5c, 0x7c, 0x16, 0xae, 0xfa, 0x4f, 0x09, 0xf6, 0x68, 0x94, 0xc6, 0x88, 0xd2,
	0x18, 0x81, 0x83, 0xda, 0x50, 0x18, 0x8f, 0x02, 0x46, 0xd8, 0xf7, 0x39, 0x0b, 0x42, 0x45, 0xaa,
	0x49, 0x8d, 0x42, 0xab, 0xa6, 0x89, 0x29, 0xb4, 0x76, 0x0a, 0x30, 0x58, 0x10, 0x8c, 0x1c, 0x46,
	0xc4, 0x20, 0xa4, 0xc2, 0xb6, 0xcd, 0x6e, 0xdd, 0x09, 0xd3, 0x6d, 0x65, 0xbd, 0x26, 0x35, 0x76,
	0xc8, 0xf2, 0x8d, 0xde, 0xc2, 0x1e, 0xf7, 0xd9, 0x6c, 0x14, 0xba, 0xdc, 0xa3, 0xf7, 0x3e, 0x53,
	0x72, 0x35, 0xa9, 0xf1, 0x5f, 0xab, 0xa2, 0x09, 0xfa, 0xfa, 0x22, 0x80, 0x64, 0xf1, 0x08, 0x41,
	0xde, 0x1e, 0x85, 0x23, 0x25, 0x1f, 0x27, 0x8e, 0xff, 0xeb, 0x3f, 0x24, 0x40, 0xa9, 0x0c, 0x3d,
	0x08, 0xe6, 0x2c, 0xd2, 0x22, 0xf2, 0x90, 0xfe, 0xc6, 0x63, 0xfd, 0x1f, 0x79, 0xe4, 0x04, 0x1e,
	0x26, 0x14, 0x93, 0x86, 0x8c, 0x42, 0x46, 0x58, 0xe0, 0x73, 0x2f, 0x60, 0xe8, 0x0d, 0x14, 0xa6,
	0xa9, 0x59, 0x91, 0x6a, 0xb9, 0x46, 0xa1, 0x55, 0x16, 0x2b, 0x89, 0x51, 0x22, 0xb6, 0xfe, 0x01,
	0x0a, 0x82, 0x0f, 0xed, 0x82, 0x14, 0xfe, 0x91, 0x22, 0x85, 0xe8, 0x00, 0x36, 0xe6, 0xfe, 0x25,
	0x0f, 0x62, 0xee, 0x79, 0xb2, 0x78, 0x20, 0x05, 0xb6, 0x6c, 0x7e, 0xe7, 0x45, 0xf6, 0x5c, 0x6c,
	0x4f, 0x9e, 0xaf, 0x7e, 0xe5, 0x60, 0x2f, 0xa3, 0x09, 0xed, 0x43, 0x61, 0xd0, 0xb3, 0x4c, 0xdc,
	0xd1, 0xdf, 0xe9, 0xb8, 0x2b, 0xaf, 0x21, 0x19, 0x76, 0x4d, 0xd2, 0x37, 0x31, 0xa1, 0x9f, 0x86,
	0x16, 0xa6, 0xb2, 0x94, 0xb1, 0xbc, 0xc7, 0x54, 0x5e, 0x47, 0x45, 0xd8, 0xb7, 0x30, 0xb9, 0xd2,
	0x3b, 0x78, 0x88, 0x3f, 0xe2, 0xce, 0x80, 0x62, 0x39, 0x87, 0x8e, 0x40, 0x59, 0xc2, 0x08, 0x36,
	0xfb, 0x84, 0x0e, 0x09, 0xb6, 0xcc, 0x7e, 0xcf, 0xc2, 0x72, 0x1e, 0x55, 0xa0, 0x84, 0xaf, 0x70,
	0x8f, 0xae, 0xb8, 0x36, 0xd0, 0x31, 0xa8, 0xdd, 0x33, 0x7a, 0x36, 0x6c, 0x9f, 0xd1, 0xce, 0xf9,
	0x8a, 0x7f, 0x13, 0xbd, 0x80, 0x67, 0xcb, 0xc4, 0x5d, 0x6c, 0xe9, 0x04, 0x77, 0x23, 0x1e, 0x29,
	0x64, 0x0b, 0xbd, 0x84, 0xda, 0x0a, 0xa4, 0x8b, 0x2f, 0x30, 0xc5, 0x29, 0x6a, 0x1b, 0x95, 0xa1,
	0xd8, 0x19, 0x58, 0xb4, 0x6f, 0x0c, 0x8d, 0x4b, 0x4a, 0x87, 0xe6, 0xa0, 0x7d, 0xa1, 0x5b, 0xe7,
	0xf2, 0x4e, 0xa4, 0xe7, 0x01, 0x75, 0xf9, 0x20, 0x62, 0x2c, 0x36, 0x22, 0x4d, 0x54, 0xca, 0xb8,
	0x32, 0x4c, 0x0e, 0xa3, 0x2e, 0x3c, 0x68, 0x4d, 0xea, 0x2d, 0x47, 0xad, 0x14, 0xbb, 0x20, 0x2b,
	0xa8, 0x04, 0xff, 0xaf, 0x88, 0x97, 0x2b, 0x48, 0x81, 0x83, 0xc7, 0x34, 0xcb, 0x2a, 0xaa, 0x42,
	0xf9, 0x09, 0xa9, 0x72, 0xb5, 0xe5, 0x40, 0x31, 0xdd, 0x82, 0x81, 0x6f, 0xb1, 0x59, 0x34, 0xec,
	0xc8, 0x14, 0xcd, 0x46, 0xe0, 0x10, 0xe6, 0xf3, 0x59, 0x88, 0x32, 0xa3, 0x9e, 0x01, 0xa8, 0x47,
	0xd9, 0x7d, 0xef, 0xc4, 0x9f, 0x64, 0x9c, 0xeb, 0x6b, 0x2d, 0x07, 0x4a, 0x69, 0x40, 0x97, 0xdf,
	0x79, 0x49, 0xa9, 0x9e, 0xb8, 0x87, 0x46, 0xe0, 0xc4, 0xab, 0x88, 0x8e, 0x1f, 0xaf, 0x94, 0xec,
	0xa9, 0x7a, 0xa8, 0x2d, 0xce, 0x97, 0x96, 0x9c, 0x2f, 0x0d, 0x47, 0xe7, 0xab, 0xbe, 0xd6, 0xfa,
	0x02, 0x48, 0x18, 0xff, 0xa4, 0xca, 0x79, 0x76, 0x29, 0x9e, 0x08, 0x57, 0x9f, 0x3f, 0xb5, 0x61,
	0x4b, 0x21, 0xed, 0xd3, 0xcf, 0xaf, 0x1d, 0x37, 0xbc, 0x9e, 0x8f, 0xb5, 0x09, 0x9f, 0x36, 0xef,
	0x5c, 0x6f, 0x72, 0x72, 0xe3, 0x7a, 0xdf, 0x9a, 0xcc, 0x76, 0xd8, 0xc9, 0xa2, 0x07, 0x27, 0x71,
	0x56, 0xe1, 0xfc, 0x8e, 0x37, 0x63, 0xcb, 0xe9, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x0b, 0xd7,
	0xae, 0xc9, 0x9e, 0x05, 0x00, 0x00,
}
